import type { MonitorItem, MonitorFormData, MonitorFormDataExtended } from "./types";
import type { MonitorTemplate } from "../components/MonitorTemplates";

export function buildEditFormData(monitor: MonitorItem): MonitorFormDataExtended {
  return {
    name: monitor.name,
    description: monitor.description ?? "",
    runbookUrl: monitor.runbookUrl ?? "",
    type: monitor.type as MonitorFormData["type"],
    target: monitor.target,
    intervalSec: monitor.intervalSec,
    confirmations: monitor.confirmations ?? 1,
    retryCount: (monitor as typeof monitor & { retryCount?: number }).retryCount ?? 0,
    enabled: monitor.enabled,
    pluginId: String(monitor.config?.pluginId ?? ""),
    expectedText: String(monitor.config?.expectedText ?? ""),
    heartbeatTimeoutMin: Number(monitor.config?.timeoutMin ?? 5),
    heartbeatToken: String(monitor.config?.token ?? ""),
    folderId: monitor.folderId ?? "",
    slaTarget: monitor.slaTarget ?? "",
    slaPeriodDays: monitor.slaPeriodDays ?? 30,
    autoIncident: monitor.autoIncident ?? false,
    autoIncidentSeverity: monitor.autoIncidentSeverity ?? "MEDIUM",
    flapDetectionEnabled: monitor.flapDetectionEnabled ?? true,
    flapWindow: monitor.flapWindow ?? 10,
    flapThreshold: monitor.flapThreshold ?? 0.5,
    latencyAlertMs: (monitor as typeof monitor & { latencyAlertMs?: number | null }).latencyAlertMs ?? null,
    anomalyDetection: (monitor as typeof monitor & { anomalyDetection?: boolean }).anomalyDetection ?? false,
    anomalyMultiplier: (monitor as typeof monitor & { anomalyMultiplier?: number }).anomalyMultiplier ?? 2.0,
    cronExpression: (monitor as typeof monitor & { cronExpression?: string | null }).cronExpression ?? '',
    scheduleEnabled: (monitor as typeof monitor & { scheduleEnabled?: boolean }).scheduleEnabled ?? false,
    scheduleDays: (monitor as typeof monitor & { scheduleDays?: string }).scheduleDays ?? '1,2,3,4,5',
    scheduleStartHour: (monitor as typeof monitor & { scheduleStartHour?: number }).scheduleStartHour ?? 8,
    scheduleEndHour: (monitor as typeof monitor & { scheduleEndHour?: number }).scheduleEndHour ?? 18,
    sliLatencyTarget: monitor.sliLatencyTarget ?? "",
    sliLatencyWindow: monitor.sliLatencyWindow ?? 7,
    rtoMinutes: (monitor as typeof monitor & { rtoMinutes?: number | null }).rtoMinutes ?? undefined,
    expectedStatus: monitor.config?.expectedStatus ? Number(monitor.config.expectedStatus) : undefined,
    bodyContains: String(monitor.config?.bodyContains ?? ""),
    httpMethod: String(monitor.config?.httpMethod ?? "GET"),
    requestHeaders: monitor.config?.requestHeaders
      ? Object.entries(monitor.config.requestHeaders as Record<string, string>).map(([k, v]) => `${k}: ${v}`).join("\n")
      : "",
    requestBody: String(monitor.config?.requestBody ?? ""),
    responseTimeThresholdMs: monitor.config?.responseTimeThresholdMs ? Number(monitor.config.responseTimeThresholdMs) : undefined,
    checkSecurityHeaders: Boolean(monitor.config?.checkSecurityHeaders),
    minResponseBodyBytes: monitor.config?.minResponseBodyBytes ? Number(monitor.config.minResponseBodyBytes) : undefined,
    maxResponseBodyBytes: monitor.config?.maxResponseBodyBytes ? Number(monitor.config.maxResponseBodyBytes) : undefined,
    assertResponseHeader: monitor.config?.assertResponseHeader ? String(monitor.config.assertResponseHeader) : undefined,
    assertResponseHeaderValue: monitor.config?.assertResponseHeaderValue ? String(monitor.config.assertResponseHeaderValue) : undefined,
    followRedirects: monitor.config?.followRedirects !== false,
    maxRedirects: monitor.config?.maxRedirects !== undefined ? Number(monitor.config.maxRedirects) : 10,
    bodyJsonPath: String(monitor.config?.bodyJsonPath ?? ""),
    bodyJsonPathExpected: String(monitor.config?.bodyJsonPathExpected ?? ""),
    ehlo: String(monitor.config?.ehlo ?? "pulsedock.monitor"),
    checkTls: Boolean(monitor.config?.checkTls),
    dnsRecordType: String(monitor.config?.recordType ?? "A"),
    dnsExpectedValue: String(monitor.config?.expectedValue ?? ""),
    dnsTimeoutMs: Number(monitor.config?.timeoutMs ?? 10000),
    dnsDetectChanges: monitor.config?.detectChanges === true,
    pingCount: Number(monitor.config?.pingCount ?? 3),
    pingMaxLossPct: monitor.config?.maxPacketLossPct !== undefined ? Number(monitor.config.maxPacketLossPct) : undefined,
    browserExpectedText: String(monitor.config?.browserExpectedText ?? ""),
    browserSelector: String(monitor.config?.browserSelector ?? ""),
    browserStatusCodesRaw: Array.isArray(monitor.config?.browserStatusCodes)
      ? (monitor.config.browserStatusCodes as number[]).join(", ")
      : "",
    // HTTP Auth
    authType: String(monitor.config?.authType ?? "none"),
    authUser: String(monitor.config?.authUser ?? ""),
    authPassword: String(monitor.config?.authPassword ?? ""),
    authToken: String(monitor.config?.authToken ?? ""),
    authApiKeyName: String(monitor.config?.authApiKeyName ?? ""),
    authApiKeyValue: String(monitor.config?.authApiKeyValue ?? ""),
    authApiKeyIn: String(monitor.config?.authApiKeyIn ?? "header"),
    trackedHeaders: (monitor as typeof monitor & { trackedHeaders?: string | null }).trackedHeaders ?? "",
    timeoutMs: (monitor as typeof monitor & { timeoutMs?: number | null }).timeoutMs ?? null,
    statusWebhookUrl: (monitor as typeof monitor & { statusWebhookUrl?: string | null }).statusWebhookUrl ?? "",
    statusWebhookSecret: "",
    throttleMs: (monitor as typeof monitor & { throttleMs?: number | null }).throttleMs ?? null,
    maxChecksPerHour: (monitor as typeof monitor & { maxChecksPerHour?: number | null }).maxChecksPerHour ?? null,
    metricPath: (monitor as typeof monitor & { metricPath?: string | null }).metricPath ?? null,
    metricName: (monitor as typeof monitor & { metricName?: string | null }).metricName ?? null,
    metricUnit: (monitor as typeof monitor & { metricUnit?: string | null }).metricUnit ?? null,
    metricAlertMin: (monitor as typeof monitor & { metricAlertMin?: number | null }).metricAlertMin ?? null,
    metricAlertMax: (monitor as typeof monitor & { metricAlertMax?: number | null }).metricAlertMax ?? null,
    graphqlQuery: (monitor as typeof monitor & { graphqlQuery?: string | null }).graphqlQuery ?? null,
    graphqlVariables: (monitor as typeof monitor & { graphqlVariables?: string | null }).graphqlVariables ?? null,
    graphqlDataPath: (monitor as typeof monitor & { graphqlDataPath?: string | null }).graphqlDataPath ?? null,
    graphqlExpectedValue: (monitor as typeof monitor & { graphqlExpectedValue?: string | null }).graphqlExpectedValue ?? null,
    downtimeCostPerHour: (monitor as typeof monitor & { downtimeCostPerHour?: number | null }).downtimeCostPerHour ?? null,
    // Pre-request auth step
    preAuthUrl: String(monitor.config?.preAuthUrl ?? ""),
    preAuthBody: String(monitor.config?.preAuthBody ?? ""),
    preAuthExtractCookie: String(monitor.config?.preAuthExtractCookie ?? ""),
    preAuthExtractToken: String(monitor.config?.preAuthExtractToken ?? ""),
  };
}

export function buildFormDataFromTemplate(t: MonitorTemplate): MonitorFormDataExtended {
  const safeType = (["HTTP", "TCP", "SSL_CERT", "HEARTBEAT", "DNS", "PING", "SMTP", "BROWSER", "FTP", "IMAP", "POP3", "CT_LOG", "GRAPHQL", "TRANSACTION"] as string[]).includes(t.type)
    ? (t.type as MonitorFormData["type"])
    : "HTTP";
  const cfg = (t.config ?? {}) as Record<string, unknown>;
  return {
    name: t.name,
    type: safeType,
    target: t.target,
    intervalSec: t.intervalSec,
    description: "",
    runbookUrl: "",
    confirmations: 1,
    retryCount: 0,
    enabled: true,
    pluginId: t.pluginId ?? "",
    expectedText: t.expectedText ?? "",
    heartbeatTimeoutMin: 5,
    heartbeatToken: "",
    folderId: "",
    slaTarget: "",
    slaPeriodDays: 30,
    autoIncident: false,
    autoIncidentSeverity: "MEDIUM",
    flapDetectionEnabled: true,
    flapWindow: 10,
    flapThreshold: 0.5,
    latencyAlertMs: null,
    anomalyDetection: false,
    anomalyMultiplier: 2.0,
    cronExpression: '',
    scheduleEnabled: false,
    scheduleDays: '1,2,3,4,5',
    scheduleStartHour: 8,
    scheduleEndHour: 18,
    sliLatencyTarget: "",
    sliLatencyWindow: 7,
    rtoMinutes: undefined,
    timeoutMs: null,
    ...(cfg.checkTls !== undefined ? { checkTls: Boolean(cfg.checkTls) } : {}),
    ...(typeof cfg.ehlo === "string" ? { ehlo: cfg.ehlo } : {}),
    ...(typeof cfg.recordType === "string" ? { dnsRecordType: cfg.recordType } : {}),
    ...(typeof cfg.expectedValue === "string" ? { dnsExpectedValue: cfg.expectedValue } : {}),
    ...(typeof cfg.timeoutMs === "number" ? { dnsTimeoutMs: cfg.timeoutMs } : {}),
    ...(typeof cfg.pingCount === "number" ? { pingCount: cfg.pingCount } : {}),
    ...(typeof cfg.maxPacketLossPct === "number" ? { pingMaxLossPct: cfg.maxPacketLossPct } : {}),
    ...(typeof cfg.browserExpectedText === "string" ? { browserExpectedText: cfg.browserExpectedText } : {}),
    ...(typeof cfg.browserSelector === "string" ? { browserSelector: cfg.browserSelector } : {}),
    ...(Array.isArray(cfg.browserStatusCodes) ? { browserStatusCodesRaw: (cfg.browserStatusCodes as number[]).join(", ") } : {}),
  };
}
