FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install

ENV NODE_ENV=development \
    API_PORT=4000 \
    DATABASE_URL=postgresql://pulsedock:pulsedock@postgres:5432/pulsedock?schema=public \
    JWT_ACCESS_SECRET=dev-access-secret-change-in-prod \
    JWT_REFRESH_SECRET=dev-refresh-secret-change-in-prod \
    APP_BASE_URL=http://localhost:3001

RUN npm run prisma:generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev -w @pulsedock/api"]
