import type { ToolRegistryEntry } from './types';

const SI = 'https://cdn.simpleicons.org'; // Simple Icons CDN

export const TOOL_REGISTRY: ToolRegistryEntry[] = [

  // ── Container ───────────────────────────────────────────────────
  {
    id: 'portainer',
    name: 'Portainer',
    category: 'Container',
    tags: ['docker', 'self-hosted', 'container'],
    icon: `${SI}/portainer`,
    description: 'Docker/Kubernetes management UI',
    homepage: 'https://portainer.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/status', jsonPath: '$.Version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'portainer/portainer' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'docker-engine',
    name: 'Docker Engine',
    category: 'Container',
    tags: ['docker', 'container', 'runtime'],
    icon: `${SI}/docker`,
    description: 'Container runtime platform',
    homepage: 'https://docker.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/version', jsonPath: '$.Version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'moby/moby' },
    checkInterval: 86400,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'Container',
    tags: ['k8s', 'orchestration', 'cloud-native'],
    icon: `${SI}/kubernetes`,
    description: 'Container orchestration system',
    homepage: 'https://kubernetes.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/version', jsonPath: '$.gitVersion', authRequired: false },
    latestSource: { type: 'github-releases', target: 'kubernetes/kubernetes' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'k3s',
    name: 'k3s',
    category: 'Container',
    tags: ['kubernetes', 'lightweight', 'edge'],
    icon: `${SI}/k3s`,
    description: 'Lightweight Kubernetes distribution',
    homepage: 'https://k3s.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/version', jsonPath: '$.gitVersion', authRequired: false },
    latestSource: { type: 'github-releases', target: 'k3s-io/k3s' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'rancher',
    name: 'Rancher',
    category: 'Container',
    tags: ['kubernetes', 'management', 'self-hosted'],
    icon: `${SI}/rancher`,
    description: 'Kubernetes management platform',
    homepage: 'https://rancher.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/v3/settings/server-version', jsonPath: '$.value', authRequired: true },
    latestSource: { type: 'github-releases', target: 'rancher/rancher' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'podman',
    name: 'Podman',
    category: 'Container',
    tags: ['container', 'daemonless', 'rootless'],
    icon: `${SI}/podman`,
    description: 'Daemonless container engine',
    homepage: 'https://podman.io',
    versionSource: { type: 'github-releases', target: 'containers/podman' },
    latestSource: { type: 'github-releases', target: 'containers/podman' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'nomad',
    name: 'Nomad',
    category: 'Container',
    tags: ['orchestration', 'hashicorp', 'workload'],
    icon: `${SI}/hashicorp`,
    description: 'Flexible workload orchestrator by HashiCorp',
    homepage: 'https://www.nomadproject.io',
    versionSource: { type: 'github-releases', target: 'hashicorp/nomad' },
    latestSource: { type: 'github-releases', target: 'hashicorp/nomad' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'k0s',
    name: 'k0s',
    category: 'Container',
    tags: ['kubernetes', 'k8s', 'lightweight', 'self-hosted'],
    icon: `${SI}/kubernetes`,
    description: 'Zero-friction Kubernetes distribution',
    homepage: 'https://k0sproject.io',
    versionSource: { type: 'github-releases', target: 'k0sproject/k0s' },
    latestSource: { type: 'github-releases', target: 'k0sproject/k0s' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'fleet',
    name: 'Fleet by Rancher',
    category: 'Container',
    tags: ['gitops', 'kubernetes', 'self-hosted'],
    icon: `${SI}/rancher`,
    description: 'GitOps at scale for Kubernetes fleets',
    homepage: 'https://fleet.rancher.io',
    versionSource: { type: 'github-releases', target: 'rancher/fleet' },
    latestSource: { type: 'github-releases', target: 'rancher/fleet' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'okd',
    name: 'OKD (OpenShift Origin)',
    category: 'Container',
    tags: ['openshift', 'kubernetes', 'redhat'],
    icon: `${SI}/redhatopenshift`,
    description: 'Community distribution of Kubernetes that powers OpenShift',
    homepage: 'https://okd.io',
    versionSource: { type: 'github-releases', target: 'openshift/okd' },
    latestSource: { type: 'github-releases', target: 'openshift/okd' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── CI/CD ───────────────────────────────────────────────────────
  {
    id: 'gitlab-ce',
    name: 'GitLab CE',
    category: 'CI/CD',
    tags: ['git', 'devops', 'self-hosted'],
    icon: `${SI}/gitlab`,
    description: 'Open-source DevOps platform',
    homepage: 'https://gitlab.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v4/version', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'gitlab-org/gitlab-foss' },
    docsUrl: 'https://docs.gitlab.com/ce/api/version.html',
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'gitea',
    name: 'Gitea',
    category: 'CI/CD',
    tags: ['git', 'self-hosted', 'forge'],
    icon: `${SI}/gitea`,
    description: 'Lightweight self-hosted Git service',
    homepage: 'https://gitea.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/settings/api', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'go-gitea/gitea' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'forgejo',
    name: 'Forgejo',
    category: 'CI/CD',
    tags: ['git', 'self-hosted', 'forge'],
    icon: `${SI}/forgejo`,
    description: 'Community-maintained Gitea fork',
    homepage: 'https://forgejo.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/settings/api', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'forgejo/forgejo' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'CI/CD',
    tags: ['ci', 'automation', 'build'],
    icon: `${SI}/jenkins`,
    description: 'Open-source automation server',
    homepage: 'https://jenkins.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/json?tree=numExecutors', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'jenkinsci/jenkins' },
    checkInterval: 86400,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'argocd',
    name: 'ArgoCD',
    category: 'CI/CD',
    tags: ['gitops', 'kubernetes', 'cd'],
    icon: `${SI}/argo`,
    description: 'Declarative GitOps CD for Kubernetes',
    homepage: 'https://argo-cd.readthedocs.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/version', jsonPath: '$.Version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'argoproj/argo-cd' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'woodpecker-ci',
    name: 'Woodpecker CI',
    category: 'CI/CD',
    tags: ['ci', 'drone', 'self-hosted'],
    icon: `${SI}/woodpeckerci`,
    description: 'Simple CI engine with great UX',
    homepage: 'https://woodpecker-ci.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/info', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'woodpecker-ci/woodpecker' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'drone-ci',
    name: 'Drone CI',
    category: 'CI/CD',
    tags: ['ci', 'pipeline', 'self-hosted'],
    icon: `${SI}/drone`,
    description: 'Container-native CI/CD platform',
    homepage: 'https://drone.io',
    versionSource: { type: 'github-releases', target: 'harness/drone' },
    latestSource: { type: 'github-releases', target: 'harness/drone' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'gocd',
    name: 'GoCD',
    category: 'CI/CD',
    tags: ['ci', 'cd', 'pipeline', 'self-hosted'],
    icon: `${SI}/gocd`,
    description: 'Open source continuous delivery server',
    homepage: 'https://www.gocd.org',
    versionSource: { type: 'github-releases', target: 'gocd/gocd' },
    latestSource: { type: 'github-releases', target: 'gocd/gocd' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'gogs',
    name: 'Gogs',
    category: 'CI/CD',
    tags: ['git', 'self-hosted', 'lightweight'],
    icon: `${SI}/gogs`,
    description: 'Painless self-hosted Git service',
    homepage: 'https://gogs.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/version', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'gogs/gogs' },
    checkInterval: 86400,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'tekton',
    name: 'Tekton Pipelines',
    category: 'CI/CD',
    tags: ['kubernetes', 'cicd', 'cloud-native'],
    icon: `${SI}/tekton`,
    description: 'Kubernetes-native CI/CD pipeline framework',
    homepage: 'https://tekton.dev',
    versionSource: { type: 'github-releases', target: 'tektoncd/pipeline' },
    latestSource: { type: 'github-releases', target: 'tektoncd/pipeline' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'fluxcd',
    name: 'Flux CD',
    category: 'CI/CD',
    tags: ['gitops', 'kubernetes', 'cncf'],
    icon: `${SI}/flux`,
    description: 'GitOps tool for keeping Kubernetes clusters in sync',
    homepage: 'https://fluxcd.io',
    versionSource: { type: 'github-releases', target: 'fluxcd/flux2' },
    latestSource: { type: 'github-releases', target: 'fluxcd/flux2' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'teamcity',
    name: 'TeamCity',
    category: 'CI/CD',
    tags: ['cicd', 'jetbrains', 'build'],
    icon: `${SI}/teamcity`,
    description: 'Powerful CI/CD tool by JetBrains',
    homepage: 'https://jetbrains.com/teamcity',
    versionSource: { type: 'docker-hub', target: 'jetbrains/teamcity-server' },
    latestSource: { type: 'docker-hub', target: 'jetbrains/teamcity-server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'concourse-ci',
    name: 'Concourse CI',
    category: 'CI/CD',
    tags: ['cicd', 'pipeline', 'self-hosted'],
    icon: `${SI}/concourse`,
    description: 'Open-source continuous integration tool',
    homepage: 'https://concourse-ci.org',
    versionSource: { type: 'github-releases', target: 'concourse/concourse' },
    latestSource: { type: 'github-releases', target: 'concourse/concourse' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Database ────────────────────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'Database',
    tags: ['sql', 'relational', 'database'],
    icon: `${SI}/postgresql`,
    description: 'Advanced open-source relational database',
    homepage: 'https://postgresql.org',
    versionSource: { type: 'apt-release', target: 'postgresql' },
    latestSource: { type: 'github-releases', target: 'postgres/postgres' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'Database',
    tags: ['sql', 'relational', 'database'],
    icon: `${SI}/mysql`,
    description: 'World\'s most popular open-source database',
    homepage: 'https://mysql.com',
    versionSource: { type: 'apt-release', target: 'mysql-server' },
    latestSource: { type: 'github-releases', target: 'mysql/mysql-server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    category: 'Database',
    tags: ['sql', 'relational', 'mysql-compatible'],
    icon: `${SI}/mariadb`,
    description: 'Community-developed MySQL fork',
    homepage: 'https://mariadb.org',
    versionSource: { type: 'apt-release', target: 'mariadb-server' },
    latestSource: { type: 'github-releases', target: 'MariaDB/server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'Database',
    tags: ['cache', 'in-memory', 'key-value'],
    icon: `${SI}/redis`,
    description: 'In-memory data structure store',
    homepage: 'https://redis.io',
    versionSource: { type: 'apt-release', target: 'redis-server' },
    latestSource: { type: 'github-releases', target: 'redis/redis' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'Database',
    tags: ['nosql', 'document', 'database'],
    icon: `${SI}/mongodb`,
    description: 'Document-oriented NoSQL database',
    homepage: 'https://mongodb.com',
    versionSource: { type: 'apt-release', target: 'mongodb' },
    latestSource: { type: 'github-releases', target: 'mongodb/mongo' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'Database',
    tags: ['search', 'analytics', 'database'],
    icon: `${SI}/elasticsearch`,
    description: 'Distributed search and analytics engine',
    homepage: 'https://elastic.co',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/', jsonPath: '$.version.number', authRequired: false },
    latestSource: { type: 'github-releases', target: 'elastic/elasticsearch' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'meilisearch',
    name: 'Meilisearch',
    category: 'Database',
    tags: ['search', 'fast', 'self-hosted'],
    icon: `${SI}/meilisearch`,
    description: 'Fast, open-source search engine',
    homepage: 'https://meilisearch.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/version', jsonPath: '$.pkgVersion', authRequired: false },
    latestSource: { type: 'github-releases', target: 'meilisearch/meilisearch' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'influxdb',
    name: 'InfluxDB',
    category: 'Database',
    tags: ['time-series', 'metrics', 'database'],
    icon: `${SI}/influxdb`,
    description: 'Purpose-built time series database',
    homepage: 'https://influxdata.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/health', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'influxdata/influxdb' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    category: 'Database',
    tags: ['analytics', 'olap', 'columnar', 'self-hosted'],
    icon: `${SI}/clickhouse`,
    description: 'Fast open-source OLAP database',
    homepage: 'https://clickhouse.com',
    versionSource: { type: 'github-releases', target: 'ClickHouse/ClickHouse' },
    latestSource: { type: 'github-releases', target: 'ClickHouse/ClickHouse' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'duckdb',
    name: 'DuckDB',
    category: 'Database',
    tags: ['analytics', 'embedded', 'olap'],
    icon: `${SI}/duckdb`,
    description: 'In-process SQL OLAP database',
    homepage: 'https://duckdb.org',
    versionSource: { type: 'github-releases', target: 'duckdb/duckdb' },
    latestSource: { type: 'github-releases', target: 'duckdb/duckdb' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'typesense',
    name: 'Typesense',
    category: 'Database',
    tags: ['search', 'full-text', 'self-hosted'],
    icon: `${SI}/typesense`,
    description: 'Fast, typo-tolerant open source search engine',
    homepage: 'https://typesense.org',
    versionSource: { type: 'github-releases', target: 'typesense/typesense' },
    latestSource: { type: 'github-releases', target: 'typesense/typesense' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'surrealdb',
    name: 'SurrealDB',
    category: 'Database',
    tags: ['multi-model', 'graph', 'document', 'self-hosted'],
    icon: `${SI}/surrealdb`,
    description: 'Multi-model cloud-native database',
    homepage: 'https://surrealdb.com',
    versionSource: { type: 'github-releases', target: 'surrealdb/surrealdb' },
    latestSource: { type: 'github-releases', target: 'surrealdb/surrealdb' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'valkey',
    name: 'Valkey',
    category: 'Database',
    tags: ['cache', 'key-value', 'redis-compatible', 'self-hosted'],
    icon: `${SI}/redis`,
    description: 'Open-source Redis-compatible in-memory data store',
    homepage: 'https://valkey.io',
    versionSource: { type: 'github-releases', target: 'valkey-io/valkey' },
    latestSource: { type: 'github-releases', target: 'valkey-io/valkey' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'timescaledb',
    name: 'TimescaleDB',
    category: 'Database',
    tags: ['timeseries', 'postgresql', 'database'],
    icon: `${SI}/timescale`,
    description: 'Time-series SQL database built on PostgreSQL',
    homepage: 'https://timescale.com',
    versionSource: { type: 'docker-hub', target: 'timescale/timescaledb' },
    latestSource: { type: 'github-releases', target: 'timescale/timescaledb' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    category: 'Database',
    tags: ['distributed', 'sql', 'database'],
    icon: `${SI}/cockroachlabs`,
    description: 'Distributed SQL database built for cloud survival',
    homepage: 'https://cockroachlabs.com',
    versionSource: { type: 'github-releases', target: 'cockroachdb/cockroach' },
    latestSource: { type: 'github-releases', target: 'cockroachdb/cockroach' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'cassandra',
    name: 'Apache Cassandra',
    category: 'Database',
    tags: ['nosql', 'distributed', 'database'],
    icon: `${SI}/apachecassandra`,
    description: 'Highly-scalable distributed NoSQL database',
    homepage: 'https://cassandra.apache.org',
    versionSource: { type: 'docker-hub', target: 'cassandra' },
    latestSource: { type: 'docker-hub', target: 'cassandra' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'Database',
    tags: ['search', 'analytics', 'elasticsearch'],
    icon: `${SI}/opensearch`,
    description: 'Open-source search and analytics suite',
    homepage: 'https://opensearch.org',
    versionSource: { type: 'github-releases', target: 'opensearch-project/OpenSearch' },
    latestSource: { type: 'github-releases', target: 'opensearch-project/OpenSearch' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'keydb',
    name: 'KeyDB',
    category: 'Database',
    tags: ['redis', 'cache', 'multithreaded'],
    icon: `${SI}/redis`,
    description: 'High performance fork of Redis with multithreading',
    homepage: 'https://keydb.dev',
    versionSource: { type: 'github-releases', target: 'Snapchat/KeyDB' },
    latestSource: { type: 'github-releases', target: 'Snapchat/KeyDB' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Observability ───────────────────────────────────────────────
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'Observability',
    tags: ['dashboards', 'metrics', 'visualization'],
    icon: `${SI}/grafana`,
    description: 'Open observability & dashboards platform',
    homepage: 'https://grafana.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/health', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'grafana/grafana' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'Observability',
    tags: ['metrics', 'monitoring', 'alerting'],
    icon: `${SI}/prometheus`,
    description: 'Systems monitoring and alerting toolkit',
    homepage: 'https://prometheus.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/status/buildinfo', jsonPath: '$.data.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'prometheus/prometheus' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'Observability',
    tags: ['uptime', 'monitoring', 'self-hosted'],
    icon: `${SI}/uptimekuma`,
    description: 'Self-hosted uptime monitoring tool',
    homepage: 'https://github.com/louislam/uptime-kuma',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/entry-page', jsonPath: '$.buildVersion', authRequired: false },
    latestSource: { type: 'github-releases', target: 'louislam/uptime-kuma' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'netdata',
    name: 'Netdata',
    category: 'Observability',
    tags: ['monitoring', 'real-time', 'metrics'],
    icon: `${SI}/netdata`,
    description: 'Real-time performance monitoring',
    homepage: 'https://netdata.cloud',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/info', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'netdata/netdata' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'victoriametrics',
    name: 'VictoriaMetrics',
    category: 'Observability',
    tags: ['metrics', 'time-series', 'prometheus-compatible'],
    icon: `${SI}/victoriametrics`,
    description: 'Fast, cost-effective monitoring solution',
    homepage: 'https://victoriametrics.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/metrics', jsonPath: '$.vm_app_version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'VictoriaMetrics/VictoriaMetrics' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'alertmanager',
    name: 'Alertmanager',
    category: 'Observability',
    tags: ['alerts', 'prometheus', 'monitoring', 'self-hosted'],
    icon: `${SI}/prometheus`,
    description: 'Prometheus alert routing and notification system',
    homepage: 'https://prometheus.io/docs/alerting/alertmanager/',
    versionSource: { type: 'github-releases', target: 'prometheus/alertmanager' },
    latestSource: { type: 'github-releases', target: 'prometheus/alertmanager' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'loki',
    name: 'Loki',
    category: 'Observability',
    tags: ['logs', 'grafana', 'log-aggregation', 'self-hosted'],
    icon: `${SI}/grafana`,
    description: 'Horizontally scalable log aggregation system',
    homepage: 'https://grafana.com/oss/loki',
    versionSource: { type: 'github-releases', target: 'grafana/loki' },
    latestSource: { type: 'github-releases', target: 'grafana/loki' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'jaeger',
    name: 'Jaeger',
    category: 'Observability',
    tags: ['tracing', 'distributed', 'opentelemetry', 'self-hosted'],
    icon: `${SI}/jaeger`,
    description: 'Open source distributed tracing platform',
    homepage: 'https://www.jaegertracing.io',
    versionSource: { type: 'github-releases', target: 'jaegertracing/jaeger' },
    latestSource: { type: 'github-releases', target: 'jaegertracing/jaeger' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'opentelemetry-collector',
    name: 'OpenTelemetry Collector',
    category: 'Observability',
    tags: ['telemetry', 'otel', 'tracing', 'metrics', 'logs'],
    icon: `${SI}/opentelemetry`,
    description: 'Vendor-agnostic telemetry data collection',
    homepage: 'https://opentelemetry.io/docs/collector/',
    versionSource: { type: 'github-releases', target: 'open-telemetry/opentelemetry-collector' },
    latestSource: { type: 'github-releases', target: 'open-telemetry/opentelemetry-collector' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'tempo',
    name: 'Grafana Tempo',
    category: 'Observability',
    tags: ['tracing', 'grafana', 'observability'],
    icon: `${SI}/grafana`,
    description: 'High scale, cost-efficient distributed tracing backend',
    homepage: 'https://grafana.com/oss/tempo',
    versionSource: { type: 'github-releases', target: 'grafana/tempo' },
    latestSource: { type: 'github-releases', target: 'grafana/tempo' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'zabbix',
    name: 'Zabbix',
    category: 'Observability',
    tags: ['monitoring', 'alerting', 'self-hosted'],
    icon: `${SI}/zabbix`,
    description: 'Enterprise open-source monitoring solution',
    homepage: 'https://zabbix.com',
    versionSource: { type: 'docker-hub', target: 'zabbix/zabbix-server-pgsql' },
    latestSource: { type: 'github-releases', target: 'zabbix/zabbix' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'nagios',
    name: 'Nagios Core',
    category: 'Observability',
    tags: ['monitoring', 'alerting', 'legacy'],
    icon: `${SI}/nagios`,
    description: 'Industry standard in IT infrastructure monitoring',
    homepage: 'https://nagios.org',
    versionSource: { type: 'github-releases', target: 'NagiosEnterprises/nagioscore' },
    latestSource: { type: 'github-releases', target: 'NagiosEnterprises/nagioscore' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'checkmk',
    name: 'Checkmk',
    category: 'Observability',
    tags: ['monitoring', 'infrastructure', 'self-hosted'],
    icon: `${SI}/checkmk`,
    description: 'Comprehensive IT monitoring solution',
    homepage: 'https://checkmk.com',
    versionSource: { type: 'github-releases', target: 'tribe29/checkmk' },
    latestSource: { type: 'github-releases', target: 'tribe29/checkmk' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'graylog',
    name: 'Graylog',
    category: 'Observability',
    tags: ['logging', 'siem', 'self-hosted'],
    icon: `${SI}/graylog`,
    description: 'Centralized log management and analysis platform',
    homepage: 'https://graylog.org',
    versionSource: { type: 'github-releases', target: 'Graylog2/graylog2-server' },
    latestSource: { type: 'github-releases', target: 'Graylog2/graylog2-server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'zipkin',
    name: 'Zipkin',
    category: 'Observability',
    tags: ['tracing', 'distributed', 'observability'],
    icon: `${SI}/openzipkin`,
    description: 'Distributed tracing system',
    homepage: 'https://zipkin.io',
    versionSource: { type: 'github-releases', target: 'openzipkin/zipkin' },
    latestSource: { type: 'github-releases', target: 'openzipkin/zipkin' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Security ────────────────────────────────────────────────────
  {
    id: 'keycloak',
    name: 'Keycloak',
    category: 'Security',
    tags: ['iam', 'sso', 'auth'],
    icon: `${SI}/keycloak`,
    description: 'Open-source identity and access management',
    homepage: 'https://keycloak.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/realms/master/.well-known/openid-configuration', jsonPath: '$.issuer', authRequired: false },
    latestSource: { type: 'github-releases', target: 'keycloak/keycloak' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'authelia',
    name: 'Authelia',
    category: 'Security',
    tags: ['auth', 'sso', '2fa'],
    icon: `${SI}/authelia`,
    description: 'Open-source authentication and authorization server',
    homepage: 'https://authelia.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/health', jsonPath: '$.status', authRequired: false },
    latestSource: { type: 'github-releases', target: 'authelia/authelia' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'authentik',
    name: 'Authentik',
    category: 'Security',
    tags: ['auth', 'sso', 'idp'],
    icon: `${SI}/authentik`,
    description: 'Open-source identity provider',
    homepage: 'https://goauthentik.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v3/root/config/', jsonPath: '$.build_hash', authRequired: false },
    latestSource: { type: 'github-releases', target: 'goauthentik/authentik' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    category: 'Security',
    tags: ['secrets', 'encryption', 'pki'],
    icon: `${SI}/vault`,
    description: 'Secrets management tool',
    homepage: 'https://vaultproject.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/v1/sys/health', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'hashicorp/vault' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    category: 'Security',
    tags: ['passwords', 'bitwarden', 'self-hosted'],
    icon: `${SI}/vaultwarden`,
    description: 'Unofficial Bitwarden-compatible server',
    homepage: 'https://github.com/dani-garcia/vaultwarden',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/config', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'dani-garcia/vaultwarden' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'crowdsec',
    name: 'CrowdSec',
    category: 'Security',
    tags: ['security', 'ips', 'threat-intelligence'],
    icon: `${SI}/crowdsec`,
    description: 'Collaborative cybersecurity platform',
    homepage: 'https://crowdsec.net',
    versionSource: { type: 'github-releases', target: 'crowdsecurity/crowdsec' },
    latestSource: { type: 'github-releases', target: 'crowdsecurity/crowdsec' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'wazuh',
    name: 'Wazuh',
    category: 'Security',
    tags: ['siem', 'security', 'monitoring', 'compliance', 'self-hosted'],
    icon: `${SI}/wazuh`,
    description: 'Open source security platform and SIEM',
    homepage: 'https://wazuh.com',
    versionSource: { type: 'github-releases', target: 'wazuh/wazuh' },
    latestSource: { type: 'github-releases', target: 'wazuh/wazuh' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'trivy',
    name: 'Trivy',
    category: 'Security',
    tags: ['vulnerability', 'scanner', 'container', 'security'],
    icon: `${SI}/aqua`,
    description: 'Comprehensive security scanner for containers and more',
    homepage: 'https://aquasecurity.github.io/trivy/',
    versionSource: { type: 'github-releases', target: 'aquasecurity/trivy' },
    latestSource: { type: 'github-releases', target: 'aquasecurity/trivy' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden Server',
    category: 'Security',
    tags: ['password-manager', 'self-hosted', 'cloud'],
    icon: `${SI}/bitwarden`,
    description: 'Open source password management solution',
    homepage: 'https://bitwarden.com',
    versionSource: { type: 'github-releases', target: 'bitwarden/server' },
    latestSource: { type: 'github-releases', target: 'bitwarden/server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'passbolt',
    name: 'Passbolt',
    category: 'Security',
    tags: ['password-manager', 'team', 'self-hosted'],
    icon: `${SI}/passbolt`,
    description: 'Open source password manager for teams',
    homepage: 'https://passbolt.com',
    versionSource: { type: 'github-releases', target: 'passbolt/passbolt_api' },
    latestSource: { type: 'github-releases', target: 'passbolt/passbolt_api' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'fail2ban',
    name: 'Fail2ban',
    category: 'Security',
    tags: ['security', 'intrusion-prevention', 'linux'],
    icon: `${SI}/linux`,
    description: 'Intrusion prevention software for Linux servers',
    homepage: 'https://fail2ban.org',
    versionSource: { type: 'github-releases', target: 'fail2ban/fail2ban' },
    latestSource: { type: 'github-releases', target: 'fail2ban/fail2ban' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'falco',
    name: 'Falco',
    category: 'Security',
    tags: ['security', 'kubernetes', 'runtime-security'],
    icon: `${SI}/falco`,
    description: 'Cloud-native runtime security and threat detection',
    homepage: 'https://falco.org',
    versionSource: { type: 'github-releases', target: 'falcosecurity/falco' },
    latestSource: { type: 'github-releases', target: 'falcosecurity/falco' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'openvas',
    name: 'OpenVAS',
    category: 'Security',
    tags: ['vulnerability-scanner', 'security', 'self-hosted'],
    icon: `${SI}/greenbone`,
    description: 'Open-source vulnerability assessment scanner',
    homepage: 'https://openvas.org',
    versionSource: { type: 'github-releases', target: 'greenbone/openvas-scanner' },
    latestSource: { type: 'github-releases', target: 'greenbone/openvas-scanner' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Networking ──────────────────────────────────────────────────
  {
    id: 'nginx',
    name: 'Nginx',
    category: 'Networking',
    tags: ['web-server', 'reverse-proxy', 'load-balancer'],
    icon: `${SI}/nginx`,
    description: 'High-performance web server and reverse proxy',
    homepage: 'https://nginx.org',
    versionSource: { type: 'apt-release', target: 'nginx' },
    latestSource: { type: 'github-releases', target: 'nginx/nginx' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'nginx-proxy-manager',
    name: 'Nginx Proxy Manager',
    category: 'Networking',
    tags: ['proxy', 'ssl', 'self-hosted'],
    icon: `${SI}/nginxproxymanager`,
    description: 'Docker-based reverse proxy with GUI',
    homepage: 'https://nginxproxymanager.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'NginxProxyManager/nginx-proxy-manager' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'traefik',
    name: 'Traefik',
    category: 'Networking',
    tags: ['proxy', 'kubernetes', 'docker'],
    icon: `${SI}/traefikproxy`,
    description: 'Cloud-native application proxy',
    homepage: 'https://traefik.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/version', jsonPath: '$.Version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'traefik/traefik' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'caddy',
    name: 'Caddy',
    category: 'Networking',
    tags: ['web-server', 'https', 'automatic-ssl'],
    icon: `${SI}/caddy`,
    description: 'Automatic HTTPS web server',
    homepage: 'https://caddyserver.com',
    versionSource: { type: 'apt-release', target: 'caddy' },
    latestSource: { type: 'github-releases', target: 'caddyserver/caddy' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'pihole',
    name: 'Pi-hole',
    category: 'Networking',
    tags: ['dns', 'ad-block', 'self-hosted'],
    icon: `${SI}/pihole`,
    description: 'Network-wide ad blocker',
    homepage: 'https://pi-hole.net',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/admin/api.php?versions', jsonPath: '$.core_current', authRequired: false },
    latestSource: { type: 'github-releases', target: 'pi-hole/pi-hole' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'adguard-home',
    name: 'AdGuard Home',
    category: 'Networking',
    tags: ['dns', 'ad-block', 'privacy'],
    icon: `${SI}/adguard`,
    description: 'Network-wide ad & tracker blocking',
    homepage: 'https://adguard.com/adguard-home',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/control/status', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'AdguardTeam/AdGuardHome' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'tailscale',
    name: 'Tailscale',
    category: 'Networking',
    tags: ['vpn', 'wireguard', 'zero-trust'],
    icon: `${SI}/tailscale`,
    description: 'Zero config VPN built on WireGuard',
    homepage: 'https://tailscale.com',
    versionSource: { type: 'apt-release', target: 'tailscale' },
    latestSource: { type: 'github-releases', target: 'tailscale/tailscale' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'haproxy',
    name: 'HAProxy',
    category: 'Networking',
    tags: ['proxy', 'load-balancer', 'high-availability'],
    icon: `${SI}/haproxy`,
    description: 'High-performance TCP/HTTP load balancer',
    homepage: 'https://www.haproxy.org',
    versionSource: { type: 'github-releases', target: 'haproxy/haproxy' },
    latestSource: { type: 'github-releases', target: 'haproxy/haproxy' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'pi-hole',
    name: 'Pi-hole',
    category: 'Networking',
    tags: ['dns', 'ad-blocking', 'self-hosted'],
    icon: `${SI}/pihole`,
    description: 'Network-wide ad blocking via DNS',
    homepage: 'https://pi-hole.net',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/info/version', jsonPath: '$.core.local.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'pi-hole/pi-hole' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'envoy',
    name: 'Envoy Proxy',
    category: 'Networking',
    tags: ['proxy', 'service-mesh', 'cncf'],
    icon: `${SI}/envoyproxy`,
    description: 'Cloud-native high-performance edge/service proxy',
    homepage: 'https://envoyproxy.io',
    versionSource: { type: 'github-releases', target: 'envoyproxy/envoy' },
    latestSource: { type: 'github-releases', target: 'envoyproxy/envoy' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'istio',
    name: 'Istio',
    category: 'Networking',
    tags: ['service-mesh', 'kubernetes', 'cncf'],
    icon: `${SI}/istio`,
    description: 'Open source service mesh for cloud-native apps',
    homepage: 'https://istio.io',
    versionSource: { type: 'github-releases', target: 'istio/istio' },
    latestSource: { type: 'github-releases', target: 'istio/istio' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'linkerd',
    name: 'Linkerd',
    category: 'Networking',
    tags: ['service-mesh', 'kubernetes', 'cncf'],
    icon: `${SI}/linkerd`,
    description: 'Ultra-light, security-first service mesh for Kubernetes',
    homepage: 'https://linkerd.io',
    versionSource: { type: 'github-releases', target: 'linkerd/linkerd2' },
    latestSource: { type: 'github-releases', target: 'linkerd/linkerd2' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'wireguard',
    name: 'WireGuard',
    category: 'Networking',
    tags: ['vpn', 'kernel', 'secure'],
    icon: `${SI}/wireguard`,
    description: 'Modern, fast, and secure VPN tunnel',
    homepage: 'https://wireguard.com',
    versionSource: { type: 'github-releases', target: 'WireGuard/wireguard-linux' },
    latestSource: { type: 'github-releases', target: 'WireGuard/wireguard-linux' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'netbird',
    name: 'NetBird',
    category: 'Networking',
    tags: ['vpn', 'wireguard', 'zero-trust'],
    icon: `${SI}/wireguard`,
    description: 'Connect your devices into a single secure private network',
    homepage: 'https://netbird.io',
    versionSource: { type: 'github-releases', target: 'netbirdio/netbird' },
    latestSource: { type: 'github-releases', target: 'netbirdio/netbird' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Storage ─────────────────────────────────────────────────────
  {
    id: 'minio',
    name: 'MinIO',
    category: 'Storage',
    tags: ['s3', 'object-storage', 'self-hosted'],
    icon: `${SI}/minio`,
    description: 'S3-compatible object storage',
    homepage: 'https://min.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/minio/health/live', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'minio/minio' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'Storage',
    tags: ['file-sync', 'collaboration', 'self-hosted'],
    icon: `${SI}/nextcloud`,
    description: 'Self-hosted productivity platform',
    homepage: 'https://nextcloud.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/status.php', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'nextcloud/server' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'syncthing',
    name: 'Syncthing',
    category: 'Storage',
    tags: ['file-sync', 'p2p', 'self-hosted'],
    icon: `${SI}/syncthing`,
    description: 'Continuous file synchronization',
    homepage: 'https://syncthing.net',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/rest/system/version', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'syncthing/syncthing' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'seafile',
    name: 'Seafile',
    category: 'Storage',
    tags: ['file-sharing', 'collaboration', 'self-hosted'],
    icon: `${SI}/seafile`,
    description: 'High-performance file hosting and sync platform',
    homepage: 'https://seafile.com',
    versionSource: { type: 'github-releases', target: 'haiwen/seafile' },
    latestSource: { type: 'github-releases', target: 'haiwen/seafile' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'truenas-scale',
    name: 'TrueNAS SCALE',
    category: 'Storage',
    tags: ['nas', 'zfs', 'self-hosted'],
    icon: `${SI}/truenas`,
    description: 'Open-source Linux-based NAS platform',
    homepage: 'https://truenas.com/truenas-scale',
    versionSource: { type: 'github-releases', target: 'truenas/scale-build' },
    latestSource: { type: 'github-releases', target: 'truenas/scale-build' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'openmediavault',
    name: 'OpenMediaVault',
    category: 'Storage',
    tags: ['nas', 'debian', 'self-hosted'],
    icon: `${SI}/debian`,
    description: 'Network attached storage solution based on Debian',
    homepage: 'https://openmediavault.org',
    versionSource: { type: 'github-releases', target: 'openmediavault/openmediavault' },
    latestSource: { type: 'github-releases', target: 'openmediavault/openmediavault' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'longhorn',
    name: 'Longhorn',
    category: 'Storage',
    tags: ['kubernetes', 'persistent-storage', 'cncf'],
    icon: `${SI}/rancher`,
    description: 'Distributed block storage for Kubernetes',
    homepage: 'https://longhorn.io',
    versionSource: { type: 'github-releases', target: 'longhorn/longhorn' },
    latestSource: { type: 'github-releases', target: 'longhorn/longhorn' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'rclone',
    name: 'Rclone',
    category: 'Storage',
    tags: ['sync', 'cloud-storage', 'backup'],
    icon: `${SI}/rclone`,
    description: 'Rsync for cloud storage — sync files to 70+ cloud services',
    homepage: 'https://rclone.org',
    versionSource: { type: 'github-releases', target: 'rclone/rclone' },
    latestSource: { type: 'github-releases', target: 'rclone/rclone' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'garage',
    name: 'Garage',
    category: 'Storage',
    tags: ['s3', 'distributed', 'self-hosted'],
    icon: `${SI}/amazons3`,
    description: 'S3-compatible distributed object storage for self-hosting',
    homepage: 'https://garagehq.deuxfleurs.fr',
    versionSource: { type: 'github-releases', target: 'deuxfleurs/garage' },
    latestSource: { type: 'github-releases', target: 'deuxfleurs/garage' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: false,
  },

  // ── CMS ─────────────────────────────────────────────────────────
  {
    id: 'wordpress',
    name: 'WordPress',
    category: 'CMS',
    tags: ['cms', 'blog', 'php'],
    icon: `${SI}/wordpress`,
    description: 'Open-source CMS powering 40% of the web',
    homepage: 'https://wordpress.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/wp-json/', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'WordPress/WordPress' },
    checkInterval: 86400,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'CMS',
    tags: ['blog', 'publishing', 'self-hosted'],
    icon: `${SI}/ghost`,
    description: 'Modern publishing platform',
    homepage: 'https://ghost.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/ghost/api/v3/site/', jsonPath: '$.site.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'TryGhost/Ghost' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'strapi',
    name: 'Strapi',
    category: 'CMS',
    tags: ['headless-cms', 'api', 'nodejs'],
    icon: `${SI}/strapi`,
    description: 'Open-source headless CMS',
    homepage: 'https://strapi.io',
    versionSource: { type: 'npm-registry', target: '@strapi/strapi' },
    latestSource: { type: 'npm-registry', target: '@strapi/strapi' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'pocketbase',
    name: 'PocketBase',
    category: 'CMS',
    tags: ['backend', 'database', 'realtime'],
    icon: `${SI}/pocketbase`,
    description: 'Open-source backend in a single file',
    homepage: 'https://pocketbase.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/health', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'pocketbase/pocketbase' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'plausible',
    name: 'Plausible Analytics',
    category: 'CMS',
    tags: ['analytics', 'privacy', 'self-hosted'],
    icon: `${SI}/plausibleanalytics`,
    description: 'Privacy-friendly Google Analytics alternative',
    homepage: 'https://plausible.io',
    versionSource: { type: 'github-releases', target: 'plausible/analytics' },
    latestSource: { type: 'github-releases', target: 'plausible/analytics' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'directus',
    name: 'Directus',
    category: 'CMS',
    tags: ['cms', 'headless', 'api'],
    icon: `${SI}/directus`,
    description: 'Open-source headless CMS & data platform',
    homepage: 'https://directus.io',
    versionSource: { type: 'github-releases', target: 'directus/directus' },
    latestSource: { type: 'github-releases', target: 'directus/directus' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'payload-cms',
    name: 'Payload CMS',
    category: 'CMS',
    tags: ['cms', 'headless', 'typescript'],
    icon: `${SI}/payloadcms`,
    description: 'Code-first headless CMS built with TypeScript and React',
    homepage: 'https://payloadcms.com',
    versionSource: { type: 'npm-registry', target: 'payload' },
    latestSource: { type: 'npm-registry', target: 'payload' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'umami',
    name: 'Umami',
    category: 'CMS',
    tags: ['analytics', 'privacy', 'self-hosted'],
    icon: `${SI}/umami`,
    description: 'Simple, fast, privacy-focused web analytics',
    homepage: 'https://umami.is',
    versionSource: { type: 'github-releases', target: 'umami-software/umami' },
    latestSource: { type: 'github-releases', target: 'umami-software/umami' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'matomo',
    name: 'Matomo',
    category: 'CMS',
    tags: ['analytics', 'gdpr', 'self-hosted'],
    icon: `${SI}/matomo`,
    description: 'Open-source web analytics platform — GDPR compliant',
    homepage: 'https://matomo.org',
    versionSource: { type: 'github-releases', target: 'matomo-org/matomo' },
    latestSource: { type: 'github-releases', target: 'matomo-org/matomo' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Communication ───────────────────────────────────────────────
  {
    id: 'mattermost',
    name: 'Mattermost',
    category: 'Communication',
    tags: ['chat', 'slack-alternative', 'self-hosted'],
    icon: `${SI}/mattermost`,
    description: 'Open-source Slack alternative',
    homepage: 'https://mattermost.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v4/system/ping', jsonPath: '$.server_version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'mattermost/mattermost' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'matrix-synapse',
    name: 'Matrix Synapse',
    category: 'Communication',
    tags: ['matrix', 'chat', 'federated'],
    icon: `${SI}/matrix`,
    description: 'Decentralised communication server',
    homepage: 'https://matrix.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/_matrix/federation/v1/version', jsonPath: '$.server.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'element-hq/synapse' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'rocketchat',
    name: 'Rocket.Chat',
    category: 'Communication',
    tags: ['chat', 'self-hosted', 'slack-alternative'],
    icon: `${SI}/rocketchat`,
    description: 'Open-source team communication platform',
    homepage: 'https://rocket.chat',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/info', jsonPath: '$.info.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'RocketChat/Rocket.Chat' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'zulip',
    name: 'Zulip',
    category: 'Communication',
    tags: ['chat', 'team', 'self-hosted'],
    icon: `${SI}/zulip`,
    description: 'Organized team chat with topics — open source',
    homepage: 'https://zulip.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/server_settings', jsonPath: '$.zulip_version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'zulip/zulip' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'discourse',
    name: 'Discourse',
    category: 'Communication',
    tags: ['forum', 'community', 'self-hosted'],
    icon: `${SI}/discourse`,
    description: 'Open source discussion platform',
    homepage: 'https://discourse.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/about.json', jsonPath: '$.about.stats.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'discourse/discourse' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'revolt',
    name: 'Revolt',
    category: 'Communication',
    tags: ['chat', 'discord-alternative', 'self-hosted'],
    icon: `${SI}/revolt`,
    description: 'Open-source Discord-alternative chat platform',
    homepage: 'https://revolt.chat',
    versionSource: { type: 'github-releases', target: 'revoltchat/backend' },
    latestSource: { type: 'github-releases', target: 'revoltchat/backend' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: false,
  },
  {
    id: 'element',
    name: 'Element Web',
    category: 'Communication',
    tags: ['matrix', 'chat', 'decentralized'],
    icon: `${SI}/element`,
    description: 'Matrix client for secure, decentralized communication',
    homepage: 'https://element.io',
    versionSource: { type: 'github-releases', target: 'element-hq/element-web' },
    latestSource: { type: 'github-releases', target: 'element-hq/element-web' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Media ───────────────────────────────────────────────────────
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    category: 'Media',
    tags: ['media-server', 'streaming', 'self-hosted'],
    icon: `${SI}/jellyfin`,
    description: 'Free software media system',
    homepage: 'https://jellyfin.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/System/Info/Public', jsonPath: '$.Version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'jellyfin/jellyfin' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    category: 'Media',
    tags: ['home-automation', 'iot', 'self-hosted'],
    icon: `${SI}/homeassistant`,
    description: 'Open-source home automation platform',
    homepage: 'https://home-assistant.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/', jsonPath: '$.message', authRequired: true },
    latestSource: { type: 'github-releases', target: 'home-assistant/core' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'immich',
    name: 'Immich',
    category: 'Media',
    tags: ['photos', 'self-hosted', 'google-photos-alternative'],
    icon: `${SI}/immich`,
    description: 'Self-hosted photo and video backup',
    homepage: 'https://immich.app',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/server/about', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'immich-app/immich' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'frigate',
    name: 'Frigate',
    category: 'Media',
    tags: ['nvr', 'security-camera', 'ai'],
    icon: `${SI}/frigate`,
    description: 'NVR with realtime AI object detection',
    homepage: 'https://frigate.video',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/version', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'blakeblackshear/frigate' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    category: 'Media',
    tags: ['music', 'streaming', 'self-hosted', 'subsonic'],
    icon: `${SI}/navidrome`,
    description: 'Modern music server and streamer',
    homepage: 'https://www.navidrome.org',
    versionSource: { type: 'github-releases', target: 'navidrome/navidrome' },
    latestSource: { type: 'github-releases', target: 'navidrome/navidrome' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    category: 'Media',
    tags: ['photos', 'ai', 'self-hosted'],
    icon: `${SI}/photoprism`,
    description: 'AI-powered photo management solution',
    homepage: 'https://photoprism.app',
    versionSource: { type: 'github-releases', target: 'photoprism/photoprism' },
    latestSource: { type: 'github-releases', target: 'photoprism/photoprism' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'plex',
    name: 'Plex Media Server',
    category: 'Media',
    tags: ['media', 'streaming', 'self-hosted'],
    icon: `${SI}/plex`,
    description: 'Organize and stream your personal media collection',
    homepage: 'https://plex.tv',
    versionSource: { type: 'docker-hub', target: 'plexinc/pms-docker' },
    latestSource: { type: 'docker-hub', target: 'plexinc/pms-docker' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'emby',
    name: 'Emby Server',
    category: 'Media',
    tags: ['media', 'streaming', 'self-hosted'],
    icon: `${SI}/emby`,
    description: 'Personal media server with streaming and management',
    homepage: 'https://emby.media',
    versionSource: { type: 'github-releases', target: 'MediaBrowser/Emby' },
    latestSource: { type: 'github-releases', target: 'MediaBrowser/Emby' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'owncast',
    name: 'Owncast',
    category: 'Media',
    tags: ['streaming', 'live', 'self-hosted'],
    icon: `${SI}/owncast`,
    description: 'Self-hosted live video and web chat server',
    homepage: 'https://owncast.online',
    versionSource: { type: 'github-releases', target: 'owncast/owncast' },
    latestSource: { type: 'github-releases', target: 'owncast/owncast' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Infrastructure ──────────────────────────────────────────────
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'Infrastructure',
    tags: ['iac', 'provisioning', 'cloud'],
    icon: `${SI}/terraform`,
    description: 'Infrastructure as Code tool',
    homepage: 'https://terraform.io',
    versionSource: { type: 'apt-release', target: 'terraform' },
    latestSource: { type: 'github-releases', target: 'hashicorp/terraform' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'opentofu',
    name: 'OpenTofu',
    category: 'Infrastructure',
    tags: ['iac', 'terraform-fork', 'open-source'],
    icon: `${SI}/opentofu`,
    description: 'Open-source Terraform fork',
    homepage: 'https://opentofu.org',
    versionSource: { type: 'github-releases', target: 'opentofu/opentofu' },
    latestSource: { type: 'github-releases', target: 'opentofu/opentofu' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'ansible',
    name: 'Ansible',
    category: 'Infrastructure',
    tags: ['automation', 'configuration-management', 'iac'],
    icon: `${SI}/ansible`,
    description: 'IT automation platform',
    homepage: 'https://ansible.com',
    versionSource: { type: 'pypi', target: 'ansible' },
    latestSource: { type: 'pypi', target: 'ansible' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'pulumi',
    name: 'Pulumi',
    category: 'Infrastructure',
    tags: ['iac', 'infrastructure', 'cloud', 'programming-languages'],
    icon: `${SI}/pulumi`,
    description: 'Infrastructure as Code using real programming languages',
    homepage: 'https://www.pulumi.com',
    versionSource: { type: 'github-releases', target: 'pulumi/pulumi' },
    latestSource: { type: 'github-releases', target: 'pulumi/pulumi' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'packer',
    name: 'Packer',
    category: 'Infrastructure',
    tags: ['image-builder', 'hashicorp', 'infrastructure'],
    icon: `${SI}/packer`,
    description: 'Machine image builder by HashiCorp',
    homepage: 'https://www.packer.io',
    versionSource: { type: 'github-releases', target: 'hashicorp/packer' },
    latestSource: { type: 'github-releases', target: 'hashicorp/packer' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'saltstack',
    name: 'SaltStack',
    category: 'Infrastructure',
    tags: ['configuration-management', 'automation', 'devops'],
    icon: `${SI}/saltproject`,
    description: 'Event-driven IT automation, remote execution, and configuration',
    homepage: 'https://saltproject.io',
    versionSource: { type: 'github-releases', target: 'saltstack/salt' },
    latestSource: { type: 'github-releases', target: 'saltstack/salt' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'chef',
    name: 'Chef Infra',
    category: 'Infrastructure',
    tags: ['configuration-management', 'automation', 'devops'],
    icon: `${SI}/chef`,
    description: 'Infrastructure automation for compliance, security, and deployments',
    homepage: 'https://chef.io',
    versionSource: { type: 'github-releases', target: 'chef/chef' },
    latestSource: { type: 'github-releases', target: 'chef/chef' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'puppet',
    name: 'Puppet',
    category: 'Infrastructure',
    tags: ['configuration-management', 'automation', 'devops'],
    icon: `${SI}/puppet`,
    description: 'Infrastructure as code automation platform',
    homepage: 'https://puppet.com',
    versionSource: { type: 'github-releases', target: 'puppetlabs/puppet' },
    latestSource: { type: 'github-releases', target: 'puppetlabs/puppet' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Messaging ───────────────────────────────────────────────────
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'Messaging',
    tags: ['message-queue', 'amqp', 'broker'],
    icon: `${SI}/rabbitmq`,
    description: 'Open-source message broker',
    homepage: 'https://rabbitmq.com',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/overview', jsonPath: '$.rabbitmq_version', authRequired: true },
    latestSource: { type: 'github-releases', target: 'rabbitmq/rabbitmq-server' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'Messaging',
    tags: ['streaming', 'event-bus', 'distributed'],
    icon: `${SI}/apachekafka`,
    description: 'Distributed event streaming platform',
    homepage: 'https://kafka.apache.org',
    versionSource: { type: 'github-releases', target: 'apache/kafka' },
    latestSource: { type: 'github-releases', target: 'apache/kafka' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'nats',
    name: 'NATS',
    category: 'Messaging',
    tags: ['messaging', 'cloud-native', 'pub-sub'],
    icon: `${SI}/natsdotio`,
    description: 'Connective technology for adaptive edge & distributed systems',
    homepage: 'https://nats.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/varz', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'nats-io/nats-server' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'redpanda',
    name: 'Redpanda',
    category: 'Messaging',
    tags: ['kafka', 'streaming', 'messaging', 'self-hosted'],
    icon: `${SI}/redpanda`,
    description: 'Kafka-compatible streaming data platform',
    homepage: 'https://redpanda.com',
    versionSource: { type: 'github-releases', target: 'redpanda-data/redpanda' },
    latestSource: { type: 'github-releases', target: 'redpanda-data/redpanda' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'mosquitto',
    name: 'Eclipse Mosquitto',
    category: 'Messaging',
    tags: ['mqtt', 'iot', 'message-broker', 'self-hosted'],
    icon: `${SI}/eclipsemosquitto`,
    description: 'Open source MQTT broker',
    homepage: 'https://mosquitto.org',
    versionSource: { type: 'github-releases', target: 'eclipse/mosquitto' },
    latestSource: { type: 'github-releases', target: 'eclipse/mosquitto' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'activemq',
    name: 'Apache ActiveMQ',
    category: 'Messaging',
    tags: ['messaging', 'jms', 'broker'],
    icon: `${SI}/apacheactivemq`,
    description: 'Multi-protocol messaging and integration patterns broker',
    homepage: 'https://activemq.apache.org',
    versionSource: { type: 'github-releases', target: 'apache/activemq' },
    latestSource: { type: 'github-releases', target: 'apache/activemq' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Dev Tools ───────────────────────────────────────────────────
  {
    id: 'n8n',
    name: 'n8n',
    category: 'Dev Tools',
    tags: ['workflow', 'automation', 'no-code'],
    icon: `${SI}/n8n`,
    description: 'Workflow automation platform',
    homepage: 'https://n8n.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/api/v1/info', jsonPath: '$.versionCli', authRequired: false },
    latestSource: { type: 'npm-registry', target: 'n8n' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'node-red',
    name: 'Node-RED',
    category: 'Dev Tools',
    tags: ['flow', 'iot', 'low-code'],
    icon: `${SI}/nodered`,
    description: 'Low-code programming for event-driven applications',
    homepage: 'https://nodered.org',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/red/settings', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'npm-registry', target: '@node-red/runtime' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Dev Tools',
    tags: ['backend', 'postgres', 'firebase-alternative'],
    icon: `${SI}/supabase`,
    description: 'Open-source Firebase alternative',
    homepage: 'https://supabase.io',
    versionSource: { type: 'github-releases', target: 'supabase/supabase' },
    latestSource: { type: 'github-releases', target: 'supabase/supabase' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    category: 'Dev Tools',
    tags: ['backend', 'baas', 'self-hosted'],
    icon: `${SI}/appwrite`,
    description: 'Open-source backend server',
    homepage: 'https://appwrite.io',
    versionSource: { type: 'json-path', urlTemplate: '{{instanceUrl}}/v1/health/version', jsonPath: '$.version', authRequired: false },
    latestSource: { type: 'github-releases', target: 'appwrite/appwrite' },
    checkInterval: 3600,
    requiresInstanceUrl: true,
    verified: true,
  },
  {
    id: 'windmill',
    name: 'Windmill',
    category: 'Dev Tools',
    tags: ['automation', 'workflow', 'scripts', 'self-hosted'],
    icon: `${SI}/windmill`,
    description: 'Open-source developer platform for scripts and workflows',
    homepage: 'https://windmill.dev',
    versionSource: { type: 'github-releases', target: 'windmill-labs/windmill' },
    latestSource: { type: 'github-releases', target: 'windmill-labs/windmill' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'temporal',
    name: 'Temporal',
    category: 'Dev Tools',
    tags: ['workflows', 'orchestration', 'durable-execution'],
    icon: `${SI}/temporal`,
    description: 'Durable execution platform for reliable workflows',
    homepage: 'https://temporal.io',
    versionSource: { type: 'github-releases', target: 'temporalio/temporal' },
    latestSource: { type: 'github-releases', target: 'temporalio/temporal' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'prefect',
    name: 'Prefect',
    category: 'Dev Tools',
    tags: ['workflow', 'orchestration', 'dataflow', 'python'],
    icon: `${SI}/prefect`,
    description: 'Modern workflow orchestration platform',
    homepage: 'https://www.prefect.io',
    versionSource: { type: 'github-releases', target: 'PrefectHQ/prefect' },
    latestSource: { type: 'github-releases', target: 'PrefectHQ/prefect' },
    checkInterval: 3600,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'code-server',
    name: 'code-server',
    category: 'Dev Tools',
    tags: ['vscode', 'browser', 'self-hosted'],
    icon: `${SI}/visualstudiocode`,
    description: 'VS Code in the browser, self-hosted',
    homepage: 'https://coder.com/docs/code-server',
    versionSource: { type: 'github-releases', target: 'coder/code-server' },
    latestSource: { type: 'github-releases', target: 'coder/code-server' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'coder',
    name: 'Coder',
    category: 'Dev Tools',
    tags: ['remote-dev', 'kubernetes', 'self-hosted'],
    icon: `${SI}/coder`,
    description: 'Cloud development environments on your infrastructure',
    homepage: 'https://coder.com',
    versionSource: { type: 'github-releases', target: 'coder/coder' },
    latestSource: { type: 'github-releases', target: 'coder/coder' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'jupyter',
    name: 'JupyterLab',
    category: 'Dev Tools',
    tags: ['notebook', 'python', 'data-science'],
    icon: `${SI}/jupyter`,
    description: 'Web-based interactive development environment for notebooks',
    homepage: 'https://jupyter.org',
    versionSource: { type: 'npm-registry', target: '@jupyterlab/application' },
    latestSource: { type: 'npm-registry', target: '@jupyterlab/application' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'airflow',
    name: 'Apache Airflow',
    category: 'Dev Tools',
    tags: ['workflow', 'orchestration', 'data-engineering'],
    icon: `${SI}/apacheairflow`,
    description: 'Platform to programmatically author, schedule, and monitor workflows',
    homepage: 'https://airflow.apache.org',
    versionSource: { type: 'github-releases', target: 'apache/airflow' },
    latestSource: { type: 'github-releases', target: 'apache/airflow' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Cloud ───────────────────────────────────────────────────────
  {
    id: 'nestjs',
    name: 'NestJS',
    category: 'Cloud',
    tags: ['nodejs', 'framework', 'typescript'],
    icon: `${SI}/nestjs`,
    description: 'Progressive Node.js framework',
    homepage: 'https://nestjs.com',
    versionSource: { type: 'npm-registry', target: '@nestjs/core' },
    latestSource: { type: 'npm-registry', target: '@nestjs/core' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'Cloud',
    tags: ['react', 'framework', 'fullstack'],
    icon: `${SI}/nextdotjs`,
    description: 'React framework for production',
    homepage: 'https://nextjs.org',
    versionSource: { type: 'npm-registry', target: 'next' },
    latestSource: { type: 'npm-registry', target: 'next' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'Cloud',
    tags: ['orm', 'database', 'typescript'],
    icon: `${SI}/prisma`,
    description: 'Next-generation Node.js and TypeScript ORM',
    homepage: 'https://prisma.io',
    versionSource: { type: 'npm-registry', target: 'prisma' },
    latestSource: { type: 'npm-registry', target: 'prisma' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Maven Central ───────────────────────────────────────────────
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'Maven Central',
    tags: ['java', 'spring', 'framework', 'maven'],
    icon: `${SI}/spring`,
    description: 'Java application framework — tracks latest release on Maven Central',
    homepage: 'https://spring.io/projects/spring-boot',
    versionSource: { type: 'maven-central', target: 'org.springframework.boot:spring-boot' },
    latestSource: { type: 'maven-central', target: 'org.springframework.boot:spring-boot' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'quarkus',
    name: 'Quarkus',
    category: 'Maven Central',
    tags: ['java', 'quarkus', 'framework', 'maven'],
    icon: `${SI}/quarkus`,
    description: 'Kubernetes-native Java framework — tracks latest release on Maven Central',
    homepage: 'https://quarkus.io',
    versionSource: { type: 'maven-central', target: 'io.quarkus:quarkus-bom' },
    latestSource: { type: 'maven-central', target: 'io.quarkus:quarkus-bom' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'micronaut',
    name: 'Micronaut',
    category: 'Maven Central',
    tags: ['java', 'micronaut', 'framework', 'maven'],
    icon: `${SI}/micronaut`,
    description: 'JVM microservices framework — tracks latest release on Maven Central',
    homepage: 'https://micronaut.io',
    versionSource: { type: 'maven-central', target: 'io.micronaut:micronaut-bom' },
    latestSource: { type: 'maven-central', target: 'io.micronaut:micronaut-bom' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'jackson-databind',
    name: 'Jackson Databind',
    category: 'Maven Central',
    tags: ['java', 'json', 'jackson', 'maven'],
    icon: `${SI}/json`,
    description: 'Java JSON data-binding library — tracks latest release on Maven Central',
    homepage: 'https://github.com/FasterXML/jackson-databind',
    versionSource: { type: 'maven-central', target: 'com.fasterxml.jackson.core:jackson-databind' },
    latestSource: { type: 'maven-central', target: 'com.fasterxml.jackson.core:jackson-databind' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'log4j',
    name: 'Log4j 2',
    category: 'Maven Central',
    tags: ['java', 'logging', 'log4j', 'maven', 'security'],
    icon: `${SI}/apachelogging`,
    description: 'Apache Log4j 2 logging framework — tracks latest patch releases (security-relevant)',
    homepage: 'https://logging.apache.org/log4j/2.x/',
    versionSource: { type: 'maven-central', target: 'org.apache.logging.log4j:log4j-core' },
    latestSource: { type: 'maven-central', target: 'org.apache.logging.log4j:log4j-core' },
    checkInterval: 43200,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── Helm ────────────────────────────────────────────────────────
  {
    id: 'helm-postgresql',
    name: 'PostgreSQL (Bitnami Helm)',
    category: 'Helm',
    tags: ['helm', 'postgresql', 'database', 'bitnami'],
    icon: `${SI}/postgresql`,
    description: 'Bitnami Helm chart for PostgreSQL — tracks latest chart version on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/bitnami/postgresql',
    versionSource: { type: 'helm-chart', target: 'bitnami/postgresql' },
    latestSource: { type: 'helm-chart', target: 'bitnami/postgresql' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-redis',
    name: 'Redis (Bitnami Helm)',
    category: 'Helm',
    tags: ['helm', 'redis', 'cache', 'bitnami'],
    icon: `${SI}/redis`,
    description: 'Bitnami Helm chart for Redis — tracks latest chart version on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/bitnami/redis',
    versionSource: { type: 'helm-chart', target: 'bitnami/redis' },
    latestSource: { type: 'helm-chart', target: 'bitnami/redis' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-ingress-nginx',
    name: 'ingress-nginx (Helm)',
    category: 'Helm',
    tags: ['helm', 'nginx', 'ingress', 'kubernetes'],
    icon: `${SI}/nginx`,
    description: 'Kubernetes ingress controller Helm chart — tracks latest on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx',
    versionSource: { type: 'helm-chart', target: 'ingress-nginx/ingress-nginx' },
    latestSource: { type: 'helm-chart', target: 'ingress-nginx/ingress-nginx' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-cert-manager',
    name: 'cert-manager (Helm)',
    category: 'Helm',
    tags: ['helm', 'cert-manager', 'tls', 'kubernetes', 'security'],
    icon: `${SI}/letsencrypt`,
    description: 'cert-manager Helm chart — tracks latest TLS certificate management chart on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/cert-manager/cert-manager',
    versionSource: { type: 'helm-chart', target: 'cert-manager/cert-manager' },
    latestSource: { type: 'helm-chart', target: 'cert-manager/cert-manager' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-prometheus',
    name: 'Prometheus (Helm)',
    category: 'Helm',
    tags: ['helm', 'prometheus', 'monitoring', 'observability'],
    icon: `${SI}/prometheus`,
    description: 'Prometheus Helm chart (prometheus-community) — tracks latest on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/prometheus-community/prometheus',
    versionSource: { type: 'helm-chart', target: 'prometheus-community/prometheus' },
    latestSource: { type: 'helm-chart', target: 'prometheus-community/prometheus' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-grafana',
    name: 'Grafana (Helm)',
    category: 'Helm',
    tags: ['helm', 'grafana', 'monitoring', 'observability'],
    icon: `${SI}/grafana`,
    description: 'Grafana Helm chart (grafana/grafana) — tracks latest on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/grafana/grafana',
    versionSource: { type: 'helm-chart', target: 'grafana/grafana' },
    latestSource: { type: 'helm-chart', target: 'grafana/grafana' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'helm-argocd',
    name: 'ArgoCD (Helm)',
    category: 'Helm',
    tags: ['helm', 'argocd', 'gitops', 'kubernetes', 'ci-cd'],
    icon: `${SI}/argo`,
    description: 'Argo CD Helm chart — tracks latest GitOps chart version on Artifact Hub',
    homepage: 'https://artifacthub.io/packages/helm/argo/argo-cd',
    versionSource: { type: 'helm-chart', target: 'argo/argo-cd' },
    latestSource: { type: 'helm-chart', target: 'argo/argo-cd' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },

  // ── API / Backend ──────────────────────────────────────────────────
  {
    id: 'kong',
    name: 'Kong Gateway',
    category: 'API',
    tags: ['api-gateway', 'proxy', 'self-hosted'],
    icon: `${SI}/kong`,
    description: 'Cloud-native API gateway and service mesh layer',
    homepage: 'https://konghq.com',
    versionSource: { type: 'github-releases', target: 'Kong/kong' },
    latestSource: { type: 'github-releases', target: 'Kong/kong' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'apisix',
    name: 'Apache APISIX',
    category: 'API',
    tags: ['api-gateway', 'proxy', 'high-performance'],
    icon: `${SI}/apacheapisix`,
    description: 'Dynamic, real-time, high-performance API gateway',
    homepage: 'https://apisix.apache.org',
    versionSource: { type: 'github-releases', target: 'apache/apisix' },
    latestSource: { type: 'github-releases', target: 'apache/apisix' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'tyk',
    name: 'Tyk Gateway',
    category: 'API',
    tags: ['api-gateway', 'api-management', 'self-hosted'],
    icon: `${SI}/tyk`,
    description: 'Open source API gateway and management platform',
    homepage: 'https://tyk.io',
    versionSource: { type: 'github-releases', target: 'TykTechnologies/tyk' },
    latestSource: { type: 'github-releases', target: 'TykTechnologies/tyk' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'hasura',
    name: 'Hasura',
    category: 'API',
    tags: ['graphql', 'api', 'real-time'],
    icon: `${SI}/hasura`,
    description: 'Instant GraphQL API on your data sources',
    homepage: 'https://hasura.io',
    versionSource: { type: 'github-releases', target: 'hasura/graphql-engine' },
    latestSource: { type: 'github-releases', target: 'hasura/graphql-engine' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'postgrest',
    name: 'PostgREST',
    category: 'API',
    tags: ['rest', 'postgresql', 'auto-api'],
    icon: `${SI}/postgresql`,
    description: 'Automatically creates a RESTful API from your PostgreSQL schema',
    homepage: 'https://postgrest.org',
    versionSource: { type: 'github-releases', target: 'PostgREST/postgrest' },
    latestSource: { type: 'github-releases', target: 'PostgREST/postgrest' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
  {
    id: 'fastify',
    name: 'Fastify',
    category: 'API',
    tags: ['nodejs', 'web-framework', 'performance'],
    icon: `${SI}/fastify`,
    description: 'Fast and low overhead web framework for Node.js',
    homepage: 'https://fastify.io',
    versionSource: { type: 'npm-registry', target: 'fastify' },
    latestSource: { type: 'npm-registry', target: 'fastify' },
    checkInterval: 86400,
    requiresInstanceUrl: false,
    verified: true,
  },
];

export function getToolById(id: string): ToolRegistryEntry | undefined {
  return TOOL_REGISTRY.find((t) => t.id === id);
}

export function searchTools(query: string, category?: string): ToolRegistryEntry[] {
  const q = query.toLowerCase().trim();
  return TOOL_REGISTRY.filter((t) => {
    const matchesCategory = !category || t.category === category;
    if (!q) return matchesCategory;
    return matchesCategory && (
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q)) ||
      t.id.includes(q)
    );
  });
}

export const TOOL_CATEGORIES = [...new Set(TOOL_REGISTRY.map((t) => t.category))].sort();
