"use client";

import { useState } from "react";
import { Zap, Server, Globe, Shield, Network, Mail, Brain, HardDrive, Database, Home, Code2, Gamepad2, BookOpen, BarChart3, LayoutDashboard, Wifi } from "lucide-react";

export interface MonitorTemplate {
  label: string;
  description: string;
  name: string;
  type: "HTTP" | "GIT_RELEASE" | "DOCKER_IMAGE" | "TCP" | "SSL_CERT" | "HEARTBEAT" | "DNS" | "PING" | "SMTP";
  target: string;
  intervalSec: number;
  pluginId?: string;
  expectedText?: string;
  config?: {
    appVersionEndpoint?: string;
    appAuthType?: 'none' | 'token';
    ehlo?: string;
    checkTls?: boolean;
    recordType?: string;
  };
  /** If true, template target is a placeholder URL and user must update it */
  requiresUrl?: boolean;
}

interface TemplateGroup {
  id: string;
  label: string;
  icon: React.ReactNode;
  templates: MonitorTemplate[];
}

const GENERAL_TEMPLATES: MonitorTemplate[] = [
  {
    label: "HTTP Health Check",
    description: "Poll any HTTP endpoint every 60s",
    name: "My API Health",
    type: "HTTP",
    target: "https://api.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "HTTP Response Match",
    description: "Verify a specific text is present in the response body",
    name: "Website Uptime",
    type: "HTTP",
    target: "https://example.com",
    intervalSec: 120,
    pluginId: "http.response-match",
    expectedText: "OK",
    requiresUrl: true,
  },
];

const VERSION_TEMPLATES: MonitorTemplate[] = [
  {
    label: "GitHub Release",
    description: "Track the latest release of any GitHub repo",
    name: "My Repo Releases",
    type: "GIT_RELEASE",
    target: "owner/repo",
    intervalSec: 3600,
  },
  {
    label: "Node.js Releases",
    description: "Track the official Node.js release",
    name: "Node.js",
    type: "GIT_RELEASE",
    target: "nodejs/node",
    intervalSec: 3600,
  },
  {
    label: "PostgreSQL Releases",
    description: "Track PostgreSQL upstream releases",
    name: "PostgreSQL",
    type: "GIT_RELEASE",
    target: "postgres/postgres",
    intervalSec: 3600,
  },
  {
    label: "Docker Hub Image",
    description: "Track latest tag of any Docker Hub image",
    name: "My Docker Image",
    type: "DOCKER_IMAGE",
    target: "library/nginx",
    intervalSec: 3600,
  },
  {
    label: "postgres:latest",
    description: "Track the official Postgres Docker image",
    name: "postgres Docker",
    type: "DOCKER_IMAGE",
    target: "library/postgres",
    intervalSec: 3600,
  },
  {
    label: "redis:latest",
    description: "Track the official Redis Docker image",
    name: "redis Docker",
    type: "DOCKER_IMAGE",
    target: "library/redis",
    intervalSec: 3600,
  },
];

/** Self-hosted app uptime templates — target is a placeholder URL, user must update it */
const SELF_HOSTED_TEMPLATES: MonitorTemplate[] = [
  // Container / Orchestration
  {
    label: "Portainer",
    description: "Portainer CE/EE health endpoint",
    name: "Portainer Health",
    type: "HTTP",
    target: "https://portainer.example.com/api/system/status",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/status', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Gitea",
    description: "Gitea instance health check",
    name: "Gitea Health",
    type: "HTTP",
    target: "https://gitea.example.com/api/healthz",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/v1/version', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "GitLab CE",
    description: "GitLab CE/-EE health endpoint",
    name: "GitLab Health",
    type: "HTTP",
    target: "https://gitlab.example.com/-/health",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/api/v4/version', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Grafana",
    description: "Grafana health API",
    name: "Grafana Health",
    type: "HTTP",
    target: "https://grafana.example.com/api/health",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/health', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Nextcloud",
    description: "Nextcloud status endpoint",
    name: "Nextcloud Health",
    type: "HTTP",
    target: "https://nextcloud.example.com/status.php",
    intervalSec: 60,
    config: { appVersionEndpoint: '/status.php', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Uptime Kuma",
    description: "Uptime Kuma uptime check",
    name: "Uptime Kuma Health",
    type: "HTTP",
    target: "https://kuma.example.com",
    intervalSec: 60,
    config: {},
    requiresUrl: true,
  },
  {
    label: "ArgoCD",
    description: "ArgoCD API server health",
    name: "ArgoCD Health",
    type: "HTTP",
    target: "https://argocd.example.com/healthz",
    intervalSec: 120,
    config: { appVersionEndpoint: '/api/version', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Vault",
    description: "HashiCorp Vault health endpoint",
    name: "Vault Health",
    type: "HTTP",
    target: "https://vault.example.com/v1/sys/health",
    intervalSec: 60,
    config: { appVersionEndpoint: '/v1/sys/health', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Mattermost",
    description: "Mattermost system ping",
    name: "Mattermost Health",
    type: "HTTP",
    target: "https://chat.example.com/api/v4/system/ping",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/v4/config/client?format=old', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Jellyfin",
    description: "Jellyfin media server health",
    name: "Jellyfin Health",
    type: "HTTP",
    target: "https://jellyfin.example.com/health",
    intervalSec: 120,
    config: { appVersionEndpoint: '/System/Info/Public', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Immich",
    description: "Immich photo server health",
    name: "Immich Health",
    type: "HTTP",
    target: "https://immich.example.com/api/server-info/ping",
    intervalSec: 120,
    // Version requires auth
    config: { appVersionEndpoint: '/api/server/info', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "n8n",
    description: "n8n workflow automation health",
    name: "n8n Health",
    type: "HTTP",
    target: "https://n8n.example.com/healthz",
    intervalSec: 120,
    // Version requires auth
    config: { appVersionEndpoint: '/rest/settings', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Traefik",
    description: "Traefik proxy health endpoint",
    name: "Traefik Health",
    type: "HTTP",
    target: "https://traefik.example.com/ping",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/version', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "MinIO",
    description: "MinIO object storage health",
    name: "MinIO Health",
    type: "HTTP",
    target: "https://minio.example.com/minio/health/live",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/api/v1/service/status', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Keycloak",
    description: "Keycloak IAM health endpoint",
    name: "Keycloak Health",
    type: "HTTP",
    target: "https://auth.example.com/health",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/admin/serverinfo', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Home Assistant",
    description: "Home Assistant API status",
    name: "Home Assistant Health",
    type: "HTTP",
    target: "https://homeassistant.example.com/api/",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/api/config', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Prometheus",
    description: "Prometheus metrics server",
    name: "Prometheus Health",
    type: "HTTP",
    target: "https://prometheus.example.com/-/healthy",
    intervalSec: 60,
    config: { appVersionEndpoint: '/api/v1/status/buildinfo', appAuthType: 'none' },
    requiresUrl: true,
  },
  {
    label: "Authentik",
    description: "Authentik SSO health check",
    name: "Authentik Health",
    type: "HTTP",
    target: "https://auth.example.com/-/health/ready/",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/-/api/v3/admin/version/', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Authelia",
    description: "Authelia auth proxy health",
    name: "Authelia Health",
    type: "HTTP",
    target: "https://auth.example.com/api/health",
    intervalSec: 60,
    // Version requires auth
    config: { appVersionEndpoint: '/api/configuration', appAuthType: 'token' },
    requiresUrl: true,
  },
  {
    label: "Plausible Analytics",
    description: "Plausible analytics server",
    name: "Plausible Health",
    type: "HTTP",
    target: "https://analytics.example.com/api/health",
    intervalSec: 120,
    // Version requires auth
    config: { appVersionEndpoint: '', appAuthType: 'token' },
    requiresUrl: true,
  },
];

const CODE_QUALITY_TEMPLATES: MonitorTemplate[] = [
  {
    label: "SonarQube",
    description: "Code quality and security analysis platform",
    name: "SonarQube Health",
    type: "HTTP",
    target: "https://your-sonarqube.example.com/api/system/status",
    intervalSec: 120,
    expectedText: "UP",
    requiresUrl: true,
  },
  {
    label: "Gitea API",
    description: "Gitea self-hosted Git service version endpoint",
    name: "Gitea Version",
    type: "HTTP",
    target: "https://your-gitea.example.com/api/v1/version",
    intervalSec: 120,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "Forgejo",
    description: "Forgejo self-hosted Git service version endpoint",
    name: "Forgejo Version",
    type: "HTTP",
    target: "https://your-forgejo.example.com/api/v1/version",
    intervalSec: 120,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "Gogs",
    description: "Gogs self-hosted Git service version endpoint",
    name: "Gogs Version",
    type: "HTTP",
    target: "https://your-gogs.example.com/api/v1/version",
    intervalSec: 120,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "Codeberg",
    description: "Codeberg instance version endpoint",
    name: "Codeberg Version",
    type: "HTTP",
    target: "https://your-codeberg.example.com/api/v1/version",
    intervalSec: 300,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "ReviewDog",
    description: "ReviewDog automated code review service health",
    name: "ReviewDog Health",
    type: "HTTP",
    target: "https://your-reviewdog.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Semgrep Server",
    description: "Semgrep static analysis server health check",
    name: "Semgrep Health",
    type: "HTTP",
    target: "https://your-semgrep.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "ESLint Daemon",
    description: "ESLint daemon server health endpoint",
    name: "ESLint Daemon Health",
    type: "HTTP",
    target: "https://your-eslint.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "PMD Server",
    description: "PMD static analysis server health check",
    name: "PMD Health",
    type: "HTTP",
    target: "https://your-pmd.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "CodeClimate",
    description: "CodeClimate code quality platform health",
    name: "CodeClimate Health",
    type: "HTTP",
    target: "https://your-codeclimate.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const SECURITY_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Vaultwarden",
    description: "Vaultwarden (Bitwarden-compatible) alive endpoint",
    name: "Vaultwarden Health",
    type: "HTTP",
    target: "https://your-vaultwarden.example.com/alive",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Bitwarden",
    description: "Bitwarden self-hosted server alive endpoint",
    name: "Bitwarden Health",
    type: "HTTP",
    target: "https://your-bitwarden.example.com/alive",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Passbolt",
    description: "Passbolt password manager health check",
    name: "Passbolt Health",
    type: "HTTP",
    target: "https://your-passbolt.example.com/healthcheck/status.json",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Trivy Server",
    description: "Trivy vulnerability scanner server health",
    name: "Trivy Health",
    type: "HTTP",
    target: "https://your-trivy.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Clair Server",
    description: "Clair container vulnerability analysis health",
    name: "Clair Health",
    type: "HTTP",
    target: "https://your-clair.example.com/healthz",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Wazuh",
    description: "Wazuh security monitoring platform",
    name: "Wazuh Health",
    type: "HTTP",
    target: "https://your-wazuh.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "CrowdSec",
    description: "CrowdSec collaborative security engine ping",
    name: "CrowdSec Health",
    type: "HTTP",
    target: "https://your-crowdsec.example.com/v1/ping",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Fail2Ban API",
    description: "Fail2Ban intrusion prevention via REST API",
    name: "Fail2Ban Health",
    type: "HTTP",
    target: "https://your-fail2ban-api.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "OpenVAS / Greenbone",
    description: "Greenbone vulnerability management login page",
    name: "OpenVAS Health",
    type: "HTTP",
    target: "https://your-openvas.example.com/login",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "OSSEC Manager",
    description: "OSSEC intrusion detection manager health",
    name: "OSSEC Health",
    type: "HTTP",
    target: "https://your-ossec.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const DNS_NETWORKING_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Pi-hole",
    description: "Pi-hole DNS ad-blocker summary API",
    name: "Pi-hole Health",
    type: "HTTP",
    target: "https://your-pihole.example.com/admin/api.php?summaryRaw",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "AdGuard Home",
    description: "AdGuard Home DNS filter status endpoint",
    name: "AdGuard Home Health",
    type: "HTTP",
    target: "https://your-adguard.example.com/control/status",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Unbound",
    description: "Unbound recursive DNS resolver health",
    name: "Unbound Health",
    type: "HTTP",
    target: "https://your-unbound.example.com/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "CoreDNS",
    description: "CoreDNS server health endpoint",
    name: "CoreDNS Health",
    type: "HTTP",
    target: "https://your-coredns.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Technitium DNS",
    description: "Technitium DNS server API endpoint",
    name: "Technitium DNS Health",
    type: "HTTP",
    target: "https://your-technitium.example.com/api/user/login",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "PowerDNS",
    description: "PowerDNS authoritative server API",
    name: "PowerDNS Health",
    type: "HTTP",
    target: "https://your-powerdns.example.com/api/v1/servers/localhost",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Blocky",
    description: "Blocky DNS proxy and ad-blocker",
    name: "Blocky Health",
    type: "HTTP",
    target: "https://your-blocky.example.com/dns-query",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "NextDNS",
    description: "NextDNS cloud-based DNS filtering",
    name: "NextDNS Health",
    type: "HTTP",
    target: "https://nextdns.io/",
    intervalSec: 300,
    requiresUrl: false,
  },
  {
    label: "Cloudflare DNS",
    description: "Cloudflare 1.1.1.1 DNS resolver uptime",
    name: "Cloudflare DNS Health",
    type: "HTTP",
    target: "https://1.1.1.1/",
    intervalSec: 300,
    requiresUrl: false,
  },
  {
    label: "Headscale",
    description: "Headscale self-hosted Tailscale control server",
    name: "Headscale Health",
    type: "HTTP",
    target: "https://your-headscale.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "DNS Lookup — A Record",
    description: "Verify your domain resolves to an A record (IPv4)",
    name: "DNS A Record Check",
    type: "DNS",
    target: "example.com:A",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "DNS Lookup — MX Record",
    description: "Verify your domain has valid MX (mail exchanger) records",
    name: "DNS MX Record Check",
    type: "DNS",
    target: "example.com:MX",
    intervalSec: 600,
    requiresUrl: true,
  },
  {
    label: "DNS Lookup — CNAME",
    description: "Verify a CNAME record resolves correctly",
    name: "DNS CNAME Check",
    type: "DNS",
    target: "www.example.com:CNAME",
    intervalSec: 600,
    requiresUrl: true,
  },
  {
    label: "Ping — Server Reachability",
    description: "ICMP ping check to verify host is reachable on the network",
    name: "Server Ping",
    type: "PING",
    target: "your-server.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Ping — Latency Monitor",
    description: "ICMP ping with latency alerting (warn >200ms, critical >1000ms)",
    name: "Latency Monitor",
    type: "PING",
    target: "192.168.1.1",
    intervalSec: 60,
    requiresUrl: true,
  },
];

const MAIL_COMMUNICATION_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Mailcow",
    description: "Mailcow dockerized mail server version status",
    name: "Mailcow Health",
    type: "HTTP",
    target: "https://your-mailcow.example.com/api/v1/get/status/version",
    intervalSec: 120,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "Mailu",
    description: "Mailu full-featured mail server",
    name: "Mailu Health",
    type: "HTTP",
    target: "https://your-mailu.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Roundcube",
    description: "Roundcube webmail client health",
    name: "Roundcube Health",
    type: "HTTP",
    target: "https://your-roundcube.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Mailpit",
    description: "Mailpit email testing tool API info",
    name: "Mailpit Health",
    type: "HTTP",
    target: "https://your-mailpit.example.com/api/v1/info",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "MailHog",
    description: "MailHog email testing tool messages API",
    name: "MailHog Health",
    type: "HTTP",
    target: "https://your-mailhog.example.com/api/v2/messages",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Stalwart Mail",
    description: "Stalwart all-in-one mail server health check",
    name: "Stalwart Health",
    type: "HTTP",
    target: "https://your-stalwart.example.com/healthz",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Gotify",
    description: "Gotify self-hosted push notification server",
    name: "Gotify Health",
    type: "HTTP",
    target: "https://your-gotify.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "ntfy",
    description: "ntfy self-hosted push notifications health",
    name: "ntfy Health",
    type: "HTTP",
    target: "https://your-ntfy.example.com/v1/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Mattermost",
    description: "Mattermost team messaging system ping",
    name: "Mattermost Ping",
    type: "HTTP",
    target: "https://your-mattermost.example.com/api/v4/system/ping",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Zulip",
    description: "Zulip team chat server settings endpoint",
    name: "Zulip Health",
    type: "HTTP",
    target: "https://your-zulip.example.com/api/v1/server_settings",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "SMTP — Port 25 (MTA)",
    description: "Check SMTP banner on port 25 (mail transfer agent, server-to-server)",
    name: "SMTP Port 25",
    type: "SMTP",
    target: "mail.example.com:25",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "SMTP — Port 587 (Submission + STARTTLS)",
    description: "Check SMTP submission port 587 with STARTTLS capability test",
    name: "SMTP Submission",
    type: "SMTP",
    target: "mail.example.com:587",
    intervalSec: 300,
    config: { checkTls: true } as MonitorTemplate['config'],
    requiresUrl: true,
  },
  {
    label: "SMTP — Port 465 (Implicit TLS)",
    description: "Check SMTP with implicit SSL/TLS on port 465",
    name: "SMTP SSL",
    type: "SMTP",
    target: "mail.example.com:465",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "Mailcow SMTP",
    description: "Mailcow dockerized mail server SMTP banner check",
    name: "Mailcow SMTP",
    type: "SMTP",
    target: "your-mailcow.example.com:587",
    intervalSec: 300,
    config: { checkTls: true } as MonitorTemplate['config'],
    requiresUrl: true,
  },
];

const AI_ML_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Ollama",
    description: "Ollama local LLM runner version endpoint",
    name: "Ollama Health",
    type: "HTTP",
    target: "https://your-ollama.example.com/api/version",
    intervalSec: 60,
    expectedText: "version",
    requiresUrl: true,
  },
  {
    label: "LocalAI",
    description: "LocalAI self-hosted AI backend readiness",
    name: "LocalAI Health",
    type: "HTTP",
    target: "https://your-localai.example.com/readyz",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "text-generation-webui",
    description: "Oobabooga text generation web UI",
    name: "Text Gen WebUI Health",
    type: "HTTP",
    target: "https://your-textgen.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Stable Diffusion WebUI",
    description: "AUTOMATIC1111 Stable Diffusion web interface",
    name: "Stable Diffusion Health",
    type: "HTTP",
    target: "https://your-sdwebui.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "ComfyUI",
    description: "ComfyUI node-based Stable Diffusion interface",
    name: "ComfyUI Health",
    type: "HTTP",
    target: "https://your-comfyui.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Open WebUI",
    description: "Open WebUI frontend for Ollama and OpenAI",
    name: "Open WebUI Health",
    type: "HTTP",
    target: "https://your-openwebui.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "LiteLLM",
    description: "LiteLLM proxy server for LLM APIs health",
    name: "LiteLLM Health",
    type: "HTTP",
    target: "https://your-litellm.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "vLLM",
    description: "vLLM high-throughput LLM serving health",
    name: "vLLM Health",
    type: "HTTP",
    target: "https://your-vllm.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Flowise",
    description: "Flowise AI flow builder ping endpoint",
    name: "Flowise Health",
    type: "HTTP",
    target: "https://your-flowise.example.com/api/v1/ping",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "n8n AI",
    description: "n8n workflow automation with AI nodes health",
    name: "n8n AI Health",
    type: "HTTP",
    target: "https://your-n8n.example.com/healthz",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const STORAGE_BACKUP_TEMPLATES: MonitorTemplate[] = [
  {
    label: "MinIO",
    description: "MinIO S3-compatible object storage live health",
    name: "MinIO Live Health",
    type: "HTTP",
    target: "https://your-minio.example.com/minio/health/live",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Nextcloud",
    description: "Nextcloud cloud storage status endpoint",
    name: "Nextcloud Storage Health",
    type: "HTTP",
    target: "https://your-nextcloud.example.com/status.php",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Seafile",
    description: "Seafile file sync and share server info",
    name: "Seafile Health",
    type: "HTTP",
    target: "https://your-seafile.example.com/api2/server-info/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Syncthing",
    description: "Syncthing continuous file synchronization ping",
    name: "Syncthing Health",
    type: "HTTP",
    target: "https://your-syncthing.example.com/rest/system/ping",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Rclone RCD",
    description: "Rclone remote control daemon health noop",
    name: "Rclone RCD Health",
    type: "HTTP",
    target: "https://your-rclone.example.com/rc/noop",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Restic REST Server",
    description: "Restic backup REST server uptime",
    name: "Restic REST Health",
    type: "HTTP",
    target: "https://your-restic.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Kopia Server",
    description: "Kopia backup server repository status",
    name: "Kopia Health",
    type: "HTTP",
    target: "https://your-kopia.example.com/api/v1/repo/status",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "TrueNAS SCALE",
    description: "TrueNAS SCALE NAS system info endpoint",
    name: "TrueNAS Health",
    type: "HTTP",
    target: "https://your-truenas.example.com/api/v2.0/system/info",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "OpenMediaVault",
    description: "OpenMediaVault NAS management interface",
    name: "OMV Health",
    type: "HTTP",
    target: "https://your-omv.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Duplicati",
    description: "Duplicati backup software server state",
    name: "Duplicati Health",
    type: "HTTP",
    target: "https://your-duplicati.example.com/api/v1/serverstate",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const DATABASE_TEMPLATES: MonitorTemplate[] = [
  {
    label: "pgAdmin",
    description: "pgAdmin PostgreSQL administration tool ping",
    name: "pgAdmin Health",
    type: "HTTP",
    target: "https://your-pgadmin.example.com/misc/ping",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Adminer",
    description: "Adminer lightweight database management UI",
    name: "Adminer Health",
    type: "HTTP",
    target: "https://your-adminer.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "CloudBeaver",
    description: "CloudBeaver web-based database manager ping",
    name: "CloudBeaver Health",
    type: "HTTP",
    target: "https://your-cloudbeaver.example.com/api/ping",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Redis Commander",
    description: "Redis Commander web management interface",
    name: "Redis Commander Health",
    type: "HTTP",
    target: "https://your-redis-commander.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "RedisInsight",
    description: "RedisInsight Redis GUI health endpoint",
    name: "RedisInsight Health",
    type: "HTTP",
    target: "https://your-redisinsight.example.com/api/v1/health",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Mongo Express",
    description: "Mongo Express web-based MongoDB admin",
    name: "Mongo Express Health",
    type: "HTTP",
    target: "https://your-mongo-express.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Elasticsearch",
    description: "Elasticsearch search engine cluster health",
    name: "Elasticsearch Health",
    type: "HTTP",
    target: "https://your-elasticsearch.example.com/",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "OpenSearch",
    description: "OpenSearch cluster health endpoint",
    name: "OpenSearch Health",
    type: "HTTP",
    target: "https://your-opensearch.example.com/_cluster/health",
    intervalSec: 60,
    requiresUrl: true,
  },
];

const IOT_HOME_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Home Assistant",
    description: "Home Assistant API status (requires Bearer token)",
    name: "Home Assistant API Health",
    type: "HTTP",
    target: "https://your-homeassistant.example.com/api/",
    intervalSec: 60,
    config: { appAuthType: "token" },
    requiresUrl: true,
  },
  {
    label: "Node-RED",
    description: "Node-RED flow automation health endpoint",
    name: "Node-RED Health",
    type: "HTTP",
    target: "https://your-nodered.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "EMQX",
    description: "EMQX MQTT broker status endpoint",
    name: "EMQX Health",
    type: "HTTP",
    target: "https://your-emqx.example.com/status",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Mosquitto",
    description: "Eclipse Mosquitto MQTT broker uptime",
    name: "Mosquitto Health",
    type: "HTTP",
    target: "https://your-mosquitto.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Zigbee2MQTT",
    description: "Zigbee2MQTT bridge frontend health",
    name: "Zigbee2MQTT Health",
    type: "HTTP",
    target: "https://your-zigbee2mqtt.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "ESPHome Dashboard",
    description: "ESPHome device management dashboard",
    name: "ESPHome Health",
    type: "HTTP",
    target: "https://your-esphome.example.com/",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Frigate",
    description: "Frigate NVR local video surveillance stats",
    name: "Frigate Health",
    type: "HTTP",
    target: "https://your-frigate.example.com/api/stats",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "OpenHAB",
    description: "OpenHAB smart home automation REST API",
    name: "OpenHAB Health",
    type: "HTTP",
    target: "https://your-openhab.example.com/rest/",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const GAME_SERVER_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Pterodactyl Panel",
    description: "Pterodactyl game server management panel",
    name: "Pterodactyl Health",
    type: "HTTP",
    target: "https://your-pterodactyl.example.com/api/client",
    intervalSec: 60,
    config: { appAuthType: "token" },
    requiresUrl: true,
  },
  {
    label: "PufferPanel",
    description: "PufferPanel game server management",
    name: "PufferPanel Health",
    type: "HTTP",
    target: "https://your-pufferpanel.example.com/api",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Crafty Controller",
    description: "Crafty Minecraft server controller API",
    name: "Crafty Health",
    type: "HTTP",
    target: "https://your-crafty.example.com/api/v2/public/",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Minecraft Java",
    description: "Minecraft Java server via SRV/TCP check",
    name: "Minecraft Server",
    type: "HTTP",
    target: "https://api.mcsrvstat.us/3/your-minecraft-host",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Pelican Panel",
    description: "Pelican game server management panel",
    name: "Pelican Health",
    type: "HTTP",
    target: "https://your-pelican.example.com/api/client",
    intervalSec: 60,
    config: { appAuthType: "token" },
    requiresUrl: true,
  },
  {
    label: "Velocity Proxy",
    description: "Velocity Minecraft proxy server health",
    name: "Velocity Health",
    type: "HTTP",
    target: "https://your-velocity.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "GameDig Status",
    description: "Multi-game server status via GameDig API",
    name: "Game Server Status",
    type: "HTTP",
    target: "https://your-gamedig.example.com/api/status",
    intervalSec: 120,
    requiresUrl: true,
  },
];

const WIKI_DOCS_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Wiki.js",
    description: "Wiki.js documentation platform GraphQL health",
    name: "Wiki.js Health",
    type: "HTTP",
    target: "https://your-wiki.example.com/healthz",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "BookStack",
    description: "BookStack wiki and documentation platform",
    name: "BookStack Health",
    type: "HTTP",
    target: "https://your-bookstack.example.com",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Outline",
    description: "Outline team knowledge base health check",
    name: "Outline Health",
    type: "HTTP",
    target: "https://your-outline.example.com/_health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "DokuWiki",
    description: "DokuWiki flat-file wiki",
    name: "DokuWiki Health",
    type: "HTTP",
    target: "https://your-dokuwiki.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "HedgeDoc",
    description: "HedgeDoc collaborative markdown editor",
    name: "HedgeDoc Health",
    type: "HTTP",
    target: "https://your-hedgedoc.example.com/status",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Docusaurus",
    description: "Docusaurus static documentation site",
    name: "Docs Site Health",
    type: "HTTP",
    target: "https://your-docs.example.com",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "Gitbook (self-hosted)",
    description: "GitBook self-hosted documentation",
    name: "GitBook Health",
    type: "HTTP",
    target: "https://your-gitbook.example.com",
    intervalSec: 300,
    requiresUrl: true,
  },
  {
    label: "Plane",
    description: "Plane project management and docs",
    name: "Plane Health",
    type: "HTTP",
    target: "https://your-plane.example.com/api/",
    intervalSec: 60,
    requiresUrl: true,
  },
];

const ANALYTICS_BI_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Metabase",
    description: "Metabase business intelligence health check",
    name: "Metabase Health",
    type: "HTTP",
    target: "https://your-metabase.example.com/api/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Apache Superset",
    description: "Apache Superset data visualization health",
    name: "Superset Health",
    type: "HTTP",
    target: "https://your-superset.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Redash",
    description: "Redash query and dashboard platform",
    name: "Redash Health",
    type: "HTTP",
    target: "https://your-redash.example.com/status.json",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "PostHog",
    description: "PostHog product analytics self-hosted",
    name: "PostHog Health",
    type: "HTTP",
    target: "https://your-posthog.example.com/_health/",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Umami",
    description: "Umami privacy-focused web analytics",
    name: "Umami Health",
    type: "HTTP",
    target: "https://your-umami.example.com/api/heartbeat",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "GoAccess",
    description: "GoAccess real-time web log analyzer",
    name: "GoAccess Health",
    type: "HTTP",
    target: "https://your-goaccess.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "GrowthBook",
    description: "GrowthBook feature flags and A/B testing",
    name: "GrowthBook Health",
    type: "HTTP",
    target: "https://your-growthbook.example.com/api/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Lightdash",
    description: "Lightdash open-source BI platform",
    name: "Lightdash Health",
    type: "HTTP",
    target: "https://your-lightdash.example.com/api/v1/health",
    intervalSec: 60,
    requiresUrl: true,
  },
];

const DASHBOARD_PORTAL_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Heimdall",
    description: "Heimdall application dashboard",
    name: "Heimdall Health",
    type: "HTTP",
    target: "https://your-heimdall.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Homer",
    description: "Homer static homelab dashboard",
    name: "Homer Health",
    type: "HTTP",
    target: "https://your-homer.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Dashy",
    description: "Dashy customizable dashboard",
    name: "Dashy Health",
    type: "HTTP",
    target: "https://your-dashy.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Homarr",
    description: "Homarr modern homelab dashboard",
    name: "Homarr Health",
    type: "HTTP",
    target: "https://your-homarr.example.com/api/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Flame",
    description: "Flame startpage/dashboard for self-hosted",
    name: "Flame Health",
    type: "HTTP",
    target: "https://your-flame.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Organizr",
    description: "Organizr HTPC/homelab services organizer",
    name: "Organizr Health",
    type: "HTTP",
    target: "https://your-organizr.example.com/api/v2/config/checkUpdate",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Cockpit",
    description: "Cockpit Linux web-based server manager",
    name: "Cockpit Health",
    type: "HTTP",
    target: "https://your-server.example.com:9090/cockpit/login",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Glances",
    description: "Glances system monitoring web dashboard",
    name: "Glances Health",
    type: "HTTP",
    target: "https://your-glances.example.com/api/4/status",
    intervalSec: 30,
    requiresUrl: true,
  },
];

const VPN_REMOTE_TEMPLATES: MonitorTemplate[] = [
  {
    label: "Headscale",
    description: "Headscale self-hosted Tailscale control server",
    name: "Headscale VPN Health",
    type: "HTTP",
    target: "https://your-headscale.example.com/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Netbird",
    description: "Netbird self-hosted WireGuard mesh VPN",
    name: "Netbird Health",
    type: "HTTP",
    target: "https://your-netbird.example.com/api/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Netmaker",
    description: "Netmaker automated WireGuard mesh network",
    name: "Netmaker Health",
    type: "HTTP",
    target: "https://your-netmaker.example.com/api/health",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "Firezone",
    description: "Firezone WireGuard-based VPN gateway",
    name: "Firezone Health",
    type: "HTTP",
    target: "https://your-firezone.example.com/healthz",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "ZeroTier Controller",
    description: "ZeroTier self-hosted network controller",
    name: "ZeroTier Health",
    type: "HTTP",
    target: "https://your-ztcontroller.example.com/status",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "Guacamole",
    description: "Apache Guacamole remote desktop gateway",
    name: "Guacamole Health",
    type: "HTTP",
    target: "https://your-guacamole.example.com/guacamole/",
    intervalSec: 60,
    requiresUrl: true,
  },
  {
    label: "RustDesk Server",
    description: "RustDesk self-hosted remote desktop",
    name: "RustDesk Health",
    type: "HTTP",
    target: "https://your-rustdesk.example.com",
    intervalSec: 120,
    requiresUrl: true,
  },
  {
    label: "MeshCentral",
    description: "MeshCentral remote device management",
    name: "MeshCentral Health",
    type: "HTTP",
    target: "https://your-meshcentral.example.com",
    intervalSec: 60,
    requiresUrl: true,
  },
];

export const MONITOR_TEMPLATES: MonitorTemplate[] = [
  ...GENERAL_TEMPLATES,
  ...SELF_HOSTED_TEMPLATES,
  ...CODE_QUALITY_TEMPLATES,
  ...SECURITY_TEMPLATES,
  ...DNS_NETWORKING_TEMPLATES,
  ...MAIL_COMMUNICATION_TEMPLATES,
  ...AI_ML_TEMPLATES,
  ...STORAGE_BACKUP_TEMPLATES,
  ...DATABASE_TEMPLATES,
  ...IOT_HOME_TEMPLATES,
  ...GAME_SERVER_TEMPLATES,
  ...WIKI_DOCS_TEMPLATES,
  ...ANALYTICS_BI_TEMPLATES,
  ...DASHBOARD_PORTAL_TEMPLATES,
  ...VPN_REMOTE_TEMPLATES,
];

const TEMPLATE_GROUPS: TemplateGroup[] = [
  {
    id: "general",
    label: "General",
    icon: <Globe className="w-4 h-4" />,
    templates: GENERAL_TEMPLATES,
  },
  {
    id: "self-hosted",
    label: "Self-Hosted Apps",
    icon: <Server className="w-4 h-4" />,
    templates: SELF_HOSTED_TEMPLATES,
  },
  {
    id: "code-quality",
    label: "Code Quality",
    icon: <Code2 className="w-4 h-4" />,
    templates: CODE_QUALITY_TEMPLATES,
  },
  {
    id: "security",
    label: "Security",
    icon: <Shield className="w-4 h-4" />,
    templates: SECURITY_TEMPLATES,
  },
  {
    id: "dns-networking",
    label: "DNS & Networking",
    icon: <Network className="w-4 h-4" />,
    templates: DNS_NETWORKING_TEMPLATES,
  },
  {
    id: "mail",
    label: "Mail & Comms",
    icon: <Mail className="w-4 h-4" />,
    templates: MAIL_COMMUNICATION_TEMPLATES,
  },
  {
    id: "ai-ml",
    label: "AI / ML",
    icon: <Brain className="w-4 h-4" />,
    templates: AI_ML_TEMPLATES,
  },
  {
    id: "storage",
    label: "Storage & Backup",
    icon: <HardDrive className="w-4 h-4" />,
    templates: STORAGE_BACKUP_TEMPLATES,
  },
  {
    id: "databases",
    label: "Databases",
    icon: <Database className="w-4 h-4" />,
    templates: DATABASE_TEMPLATES,
  },
  {
    id: "iot",
    label: "IoT & Home",
    icon: <Home className="w-4 h-4" />,
    templates: IOT_HOME_TEMPLATES,
  },
  {
    id: "games",
    label: "Game Servers",
    icon: <Gamepad2 className="w-4 h-4" />,
    templates: GAME_SERVER_TEMPLATES,
  },
  {
    id: "wikis",
    label: "Wikis & Docs",
    icon: <BookOpen className="w-4 h-4" />,
    templates: WIKI_DOCS_TEMPLATES,
  },
  {
    id: "analytics",
    label: "Analytics & BI",
    icon: <BarChart3 className="w-4 h-4" />,
    templates: ANALYTICS_BI_TEMPLATES,
  },
  {
    id: "dashboards",
    label: "Dashboards",
    icon: <LayoutDashboard className="w-4 h-4" />,
    templates: DASHBOARD_PORTAL_TEMPLATES,
  },
  {
    id: "vpn",
    label: "VPN & Remote",
    icon: <Wifi className="w-4 h-4" />,
    templates: VPN_REMOTE_TEMPLATES,
  },
];

interface Props {
  onSelect: (template: MonitorTemplate) => void;
}

const TYPE_COLORS: Record<MonitorTemplate["type"], string> = {
  HTTP: "text-blue-400",
  GIT_RELEASE: "text-purple-400",
  DOCKER_IMAGE: "text-cyan-400",
  TCP: "text-green-400",
  SSL_CERT: "text-yellow-400",
  HEARTBEAT: "text-orange-400",
  DNS: "text-teal-400",
  PING: "text-emerald-400",
  SMTP: "text-pink-400",
};

const TYPE_LABELS: Record<MonitorTemplate["type"], string> = {
  HTTP: "HTTP",
  GIT_RELEASE: "Git",
  DOCKER_IMAGE: "Docker",
  TCP: "TCP",
  SSL_CERT: "SSL",
  HEARTBEAT: "Heartbeat",
  DNS: "DNS",
  PING: "Ping",
  SMTP: "SMTP",
};

export function MonitorTemplates({ onSelect }: Props) {
  const [activeGroup, setActiveGroup] = useState("general");
  const group = TEMPLATE_GROUPS.find((g) => g.id === activeGroup) ?? TEMPLATE_GROUPS[0];

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 text-text-secondary">
        <Zap className="w-4 h-4" />
        <span className="text-sm font-medium">Quick Templates</span>
      </div>

      {/* Group tabs */}
      <div className="flex gap-1 rounded-lg bg-surface p-1 border border-border">
        {TEMPLATE_GROUPS.map((g) => (
          <button
            key={g.id}
            type="button"
            onClick={() => setActiveGroup(g.id)}
            className={`flex items-center gap-1.5 flex-1 justify-center px-2 py-1.5 text-xs font-medium rounded-md transition-all ${
              activeGroup === g.id
                ? "bg-bg text-text-primary shadow-sm border border-border"
                : "text-text-secondary hover:text-text-primary"
            }`}
          >
            {g.icon}
            <span className="hidden sm:inline">{g.label}</span>
          </button>
        ))}
      </div>

      {/* Self-hosted notice */}
      {activeGroup !== "general" && (
        <p className="text-xs text-text-secondary bg-surface rounded-lg px-3 py-2 border border-border">
          💡 Replace <code className="text-accent font-mono">your-service.example.com</code> with your instance domain after selecting.
        </p>
      )}

      <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
        {group.templates.map((t) => (
          <button
            key={`${t.type}-${t.label}`}
            type="button"
            onClick={() => onSelect(t)}
            className="text-left px-3 py-2.5 rounded-lg border border-border hover:border-accent/40 hover:bg-surface-elevated/60 transition-all group"
          >
            <div className="flex items-start justify-between gap-2">
              <span className="text-sm font-medium text-text-primary group-hover:text-accent transition-colors leading-snug">
                {t.label}
              </span>
              <span className={`text-[10px] font-semibold uppercase tracking-wider shrink-0 mt-0.5 ${TYPE_COLORS[t.type]}`}>
                {TYPE_LABELS[t.type]}
              </span>
            </div>
            <p className="text-xs text-text-secondary mt-0.5 leading-snug">{t.description}</p>
          </button>
        ))}
      </div>
    </div>
  );
}
