apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsedock.fullname" . }}-api
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "pulsedock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
