{{- if .Values.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pulsedock.fullname" . }}-api
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pulsedock.fullname" . }}-api
  minReplicas: {{ .Values.hpa.api.minReplicas }}
  maxReplicas: {{ .Values.hpa.api.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.api.cpuUtilization }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pulsedock.fullname" . }}-web
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pulsedock.fullname" . }}-web
  minReplicas: {{ .Values.hpa.web.minReplicas }}
  maxReplicas: {{ .Values.hpa.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.web.cpuUtilization }}
{{- end }}
