{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsedock.fullname" . }}-redis
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "pulsedock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
{{- end }}
