apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulsedock.fullname" . }}-secrets
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | b64enc | quote }}
  DEFAULT_ADMIN_EMAIL: {{ .Values.secrets.defaultAdminEmail | b64enc | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.defaultAdminPassword | b64enc | quote }}

  {{- $dbUrl := include "pulsedock.databaseUrl" . }}
  {{- if $dbUrl }}
  DATABASE_URL: {{ $dbUrl | b64enc | quote }}
  {{- end }}

  {{- $redisUrl := include "pulsedock.redisUrl" . }}
  {{- if $redisUrl }}
  REDIS_URL: {{ $redisUrl | b64enc | quote }}
  {{- end }}

  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
