apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulsedock.fullname" . }}-web
  namespace: {{ include "pulsedock.namespace" . }}
  labels:
    {{- include "pulsedock.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "pulsedock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
