apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulsedock
  labels:
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - host: pulsedock.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pulsedock-web
                port:
                  number: 1234
