apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulsedock

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: pulsedock
  app.kubernetes.io/part-of: pulsedock
