export type WidgetType =
  | 'uptime-bar'
  | 'uptime-timeline'
  | 'response-time-chart'
  | 'response-time-heatmap'
  | 'current-status-badge'
  | 'multi-monitor-status-grid'
  | 'incident-history'
  | 'active-incident-banner'
  | 'monitor-group-status'
  | 'monitor-group'
  | 'overall-system-status'
  | 'sla-summary'
  | 'check-history-feed'
  | 'text-block'
  | 'scheduled-maintenance'
  | 'last-updated-footer'
  | 'metric-counter'
  | 'divider'
  | 'version-status-grid'
  | 'version-check-badge'
  | 'update-summary'
  | 'multi-status-badges'
  | 'component-status-list'
  | 'rolling-uptime-cards'
  | 'status-history-ribbon'
  | 'uptime-percentage-card'
  | 'service-health-matrix'
  | 'aggregate-health-score'
  | 'latency-percentiles-card'
  | 'downtime-log'
  | 'active-incident-count'
  | 'mttr-mttf-cards'
  | 'sla-compliance-table'
  | 'uptime-heatmap'
  | 'incident-timeline'
  | 'ssl-certificate-status'
  | 'incident-severity-distribution'
  | 'incident-duration-stats'
  | 'post-mortem-card'
  | 'performance-trend'
  | 'apdex-score'
  | 'throughput-counter'
  | 'response-time-comparison'
  | 'uptime-comparison-chart'
  | 'next-maintenance-countdown'
  | 'maintenance-impact-list'
  | 'version-timeline'
  | 'outdated-components-alert'
  | 'version-comparison-table'
  | 'dns-resolution-time'
  | 'gauge'
  | 'stats-grid'
  | 'metric-comparison-row'
  | 'sparkline-row'
  | 'progress-ring'
  | 'announcement-bar'
  | 'link-list'
  | 'faq-accordion'
  | 'social-links'
  | 'embed-iframe'
  | 'subscriber-form'
  | 'countdown'
  | 'maintenance-calendar'
  | 'changelog-widget'
  | 'image-banner'
  | 'data-table'
  | 'rss-feed-widget'
  | 'code-block'
  | 'video-embed'
  | 'dependency-map'
  | 'multi-environment-status'
  | 'tab-container';

export interface Widget {
  id: string;
  type: WidgetType;
  x: number;
  y: number;
  w: number;
  h: number;
  config: Record<string, unknown>;
}

export interface PageLayout {
  widgets: Widget[];
}
